#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Template
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Template/PageEdit.cshtml")]
    public partial class PageEdit : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.TemplateModels.PageEditModel>
    {
        public PageEdit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
  
    ViewBag.Selected = "Settings";
    ViewBag.SelectedTab = "PageType";


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.template.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.regiontemplate.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/ext/json2.js""></script>
    <script type=""text/javascript"">
        /**
         * This var is needed by the regiontemplate script.
         */
        var templateid = '");


            
            #line 15 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                     Write(Model.Template.Id);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n        $(document).ready(function () {\r\n            $(\'#Template_Name\').fo" +
"cus();\r\n        });\r\n    </script>\r\n");


            
            #line 21 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
     if (Model.Template.IsLocked) {

            
            #line default
            #line hidden
WriteLiteral("    <style type=\"text/css\">\r\n        .region-editor .icon {\r\n            display:" +
" none;\r\n        }\r\n        .region-editor tr.dark {\r\n            display: none;\r" +
"\n        }\r\n    </style>\r\n");


            
            #line 30 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
    }

            
            #line default
            #line hidden

});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 33 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n");


            
            #line 37 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
             if (!Model.Template.IsLocked) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a class=\"save submit\">");


            
            #line 38 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");



WriteLiteral("            <li><a href=\"");


            
            #line 39 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                    Write(Url.Action("deletepage", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\" title=\"\">");


            
            #line 39 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                                                                       Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 40 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 41 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                    Write(Url.Action("pagelist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 41 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                          Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 42 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                    Write(Url.Action("page", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 42 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                                                         Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n\r\n");


            
            #line 49 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
   Html.BeginForm("page", "template") ; 

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 51 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 52 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 53 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.IsSiteTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 54 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 55 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 56 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 57 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
     if (!Piranha.Application.Current.IsMvc) {
    
            
            #line default
            #line hidden
            
            #line 58 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.View));

            
            #line default
            #line hidden
            
            #line 58 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 59 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.ShowView));

            
            #line default
            #line hidden
            
            #line 59 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                             
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div class=\"grid_9\">\r\n    <div class=\"box expandable\">\r\n        <div clas" +
"s=\"title\"><h2>");


            
            #line 64 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 67 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 69 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 70 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>");


            
            #line 72 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 74 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Description, 
                            new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n            <ul class=\"form opt" +
"ional\">               \r\n                <li>");


            
            #line 79 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Preview));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 81 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Preview, new { @rows = 8} ));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>                \r\n            </ul>\r\n        </div>\r" +
"\n    </div>\r\n    <div class=\"box content-editor\">\r\n        <div class=\"title\"><h" +
"2>");


            
            #line 87 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Piranha.Resources.Global.Regions);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <table class=\"list region-e" +
"ditor\">\r\n                <tbody>\r\n                    <tr>\r\n                    " +
"    <th>");


            
            #line 92 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                       Write(Piranha.Resources.Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th>");


            
            #line 93 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                       Write(Piranha.Resources.Global.InternalId);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th>");


            
            #line 94 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                       Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                        <th></th>\r\n                    </tr>\r\n            " +
"        ");


            
            #line 97 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.EditorFor(m => m.Regions));

            
            #line default
            #line hidden
WriteLiteral(@"
                    <tr class=""dark"">
                        <td class=""form"">
                            <div class=""input"">
                                <input type=""text"" id=""newregionName"" /></div>
                        </td>
                        <td class=""form"">
                            <div class=""input"">
                                <input type=""text"" id=""newregionInternalId"" /></div>
                        </td>
                        <td class=""form"">
                            <div class=""input"">
                                ");


            
            #line 109 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                           Write(Html.DropDownList("newregionType",
                                    new SelectList(Model.RegionTypes, "Type", "Name")));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        </td>\r\n                        <td class=\"buttons" +
" four\">\r\n                            <button id=\"btnAddRegion\" class=\"btn marg-b" +
"ig\">");


            
            #line 113 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                                      Write(Piranha.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        </td>\r\n                    </tr>\r\n            " +
"    </tbody>\r\n            </table>\r\n        </div>\r\n    </div>\r\n    <div class=\"" +
"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 121 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Piranha.Resources.Global.Advanced);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 124 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Controller, 
                        Piranha.Application.Current.IsMvc ? Piranha.Resources.Page.Route : Piranha.Resources.Page.Template));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 127 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Controller, 
                            new { @placeholder = "Page" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <label>&nbsp;</label>\r\n                    <p>");


            
            #line 130 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.ShowController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 131 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                    Write(Piranha.Application.Current.IsMvc ? Piranha.Resources.Template.PageRouteOverride : Piranha.Resources.Template.PageTemplateOverride);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </li>\r\n");


            
            #line 133 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                 if (Piranha.Application.Current.IsMvc) {

            
            #line default
            #line hidden
WriteLiteral("                <li>");


            
            #line 134 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.View));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 136 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.View, new { @placeholder = "Index" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <label>&nbsp;</label>\r\n                    <p>");


            
            #line 138 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.ShowView));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 138 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                              Write(Piranha.Resources.Template.PageViewOverride);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </li>\r\n");


            
            #line 140 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li>");


            
            #line 141 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Redirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 143 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Redirect, 
                            new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <label>&nbsp;</label>\r\n                    <p>");


            
            #line 146 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.ShowRedirect));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 146 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                                  Write(Piranha.Resources.Template.PageRedirectOverride);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div" +
">\r\n<div class=\"grid_3\">\r\n");


            
            #line 153 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
     if (!Model.Template.IsNew && !String.IsNullOrEmpty(Model.Template.Preview.ToHtmlString())) {

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box pagetemplate\">\r\n        <div class=\"title\"><h2>");


            
            #line 155 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Piranha.Resources.Page.HtmlPreview);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <div class=\"edit\">\r\n       " +
"         ");


            
            #line 158 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
           Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");


            
            #line 162 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 164 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                          Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <div id=\"region_data\"></div" +
">\r\n            <ul id=\"properties\" class=\"list buttons\">\r\n");


            
            #line 168 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                 foreach (var property in Model.Template.Properties) {

            
            #line default
            #line hidden
WriteLiteral("                <li><span>");


            
            #line 169 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                     Write(property);

            
            #line default
            #line hidden
WriteLiteral("</span><button class=\"btn delete right remove-region\"></button></li>\r\n");


            
            #line 170 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n            <div class=\"input\">\r\n                <input id=\"po" +
"_name\" type=\"text\" placeholder=\"");


            
            #line 173 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                                        Write(Piranha.Resources.Template.PropertyPlaceholder);

            
            #line default
            #line hidden
WriteLiteral("\" /></div>\r\n            <button id=\"po_add\" class=\"btn right\">");


            
            #line 174 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
                                             Write(Piranha.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            <div class=\"clear\"></div>\r\n         </div>\r\n    </div>\r\n</" +
"div>\r\n");


            
            #line 179 "..\..\Areas\Manager\Views\Template\PageEdit.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
