#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Template
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Template/PostEdit.cshtml")]
    public partial class PostEdit : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.TemplateModels.PostEditModel>
    {
        public PostEdit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
  
    ViewBag.Selected = "Settings";
    ViewBag.SelectedTab = "PostType";


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 8 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                   Write(Href("~/res.ashx/areas/manager/content/js/jquery.template.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\">\r\n        $(document).ready(funct" +
"ion () {\r\n            $(\'#Template_Name\').focus();\r\n        });\r\n    </script>\r\n" +
"");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 16 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n");


            
            #line 20 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
             if (!Model.Template.IsLocked) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a class=\"save submit\">");


            
            #line 21 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");



WriteLiteral("            <li><a href=\"");


            
            #line 22 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                    Write(Url.Action("deletepost", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 22 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                                                              Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 24 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                    Write(Url.Action("postlist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 24 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                          Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 25 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                    Write(Url.Action("post", new { id = Model.Template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 25 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                                                         Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n");


            
            #line 31 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
   Html.BeginForm("post", "template") ; 

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 33 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 34 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 35 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 36 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 37 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 38 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 39 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 40 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 41 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 42 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 43 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
     if (!Piranha.Application.Current.IsMvc) {
    
            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.View));

            
            #line default
            #line hidden
            
            #line 44 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
Write(Html.HiddenFor(m => m.Template.ShowView));

            
            #line default
            #line hidden
            
            #line 45 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                             
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div class=\"grid_9\">\r\n    <div class=\"box expandable\">\r\n        <div clas" +
"s=\"title\"><h2>");


            
            #line 50 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                          Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 54 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 56 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 57 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Template.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li class=\"protected\">\r\n                " +
"    ");


            
            #line 60 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 61 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                 	if (!Model.Permalink.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("                    <p>");


            
            #line 62 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                  Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
WriteLiteral("/");


            
            #line 62 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                             Write(Model.HandlerPrefix);

            
            #line default
            #line hidden

            
            #line 62 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                                                  Write(Url.GetPermalink(Model.Permalink.Name).ToLower());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 63 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                    } else {

            
            #line default
            #line hidden
WriteLiteral("                    <p><i>");


            
            #line 64 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                     Write(Piranha.Resources.Page.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");


            
            #line 65 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"input\">\r\n                        ");


            
            #line 67 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 68 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <a class=\"locked\"></a>\r\n                </li>\r\n            " +
"    <li>\r\n                    ");


            
            #line 72 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 74 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Description, 
                            new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n            <ul class=\"form opt" +
"ional\">               \r\n                <li>");


            
            #line 79 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Preview));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 81 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextAreaFor(m => m.Template.Preview, new { @rows = 8} ));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>                \r\n            </ul>\r\n        </div>\r" +
"\n    </div>\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 87 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                          Write(Piranha.Resources.Global.Advanced);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 90 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.Controller,
                        Piranha.Application.Current.IsMvc ? Piranha.Resources.Post.Route : Piranha.Resources.Post.Template));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 93 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.Controller, 
                            new { @placeholder = "Post" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <label>&nbsp;</label>\r\n                    <p>");


            
            #line 96 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.ShowController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 97 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                    Write(Piranha.Application.Current.IsMvc ? Piranha.Resources.Template.PostRouteOverride : Piranha.Resources.Template.PostTemplateOverride);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </li>\r\n");


            
            #line 99 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                 if (Piranha.Application.Current.IsMvc) {

            
            #line default
            #line hidden
WriteLiteral("                <li>");


            
            #line 100 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.View));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 102 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.View, new { @placeholder = "Index" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <label>&nbsp;</label>\r\n                    <p>");


            
            #line 104 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.ShowView));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 104 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                              Write(Piranha.Resources.Template.PostViewOverride);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </li>\r\n");


            
            #line 106 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                <li>");


            
            #line 107 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.ArchiveController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 109 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                   Write(Html.TextBoxFor(m => m.Template.ArchiveController, 
                            new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <label>&nbsp;</label>\r\n                    <p>");


            
            #line 112 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.ShowArchiveController));

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 112 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                                           Write(Piranha.Resources.Template.PostRedirectOverride);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 115 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
               Write(Html.LabelFor(m => m.Template.AllowRss));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <p>");


            
            #line 116 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                  Write(Html.CheckBoxFor(m => m.Template.AllowRss));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 116 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                               Write(Piranha.Resources.Template.AllowRssDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</di" +
"v>\r\n<div class=\"grid_3\">\r\n");


            
            #line 123 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
     if (!Model.Template.IsNew && !String.IsNullOrEmpty(Model.Template.Preview.ToHtmlString())) {

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box pagetemplate\">\r\n        <div class=\"title\"><h2>");


            
            #line 125 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                          Write(Piranha.Resources.Page.HtmlPreview);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <div class=\"edit\">\r\n       " +
"         ");


            
            #line 128 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
           Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");


            
            #line 132 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 134 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                          Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <div id=\"region_data\"></div" +
">\r\n            <ul id=\"properties\" class=\"list buttons\">\r\n");


            
            #line 138 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                 foreach (var property in Model.Template.Properties) {

            
            #line default
            #line hidden
WriteLiteral("                <li><span>");


            
            #line 139 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                     Write(property);

            
            #line default
            #line hidden
WriteLiteral("</span><button class=\"btn delete right remove-region\"></button></li>\r\n");


            
            #line 140 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n            <div class=\"input\">\r\n                <input id=\"po" +
"_name\" type=\"text\" placeholder=\"");


            
            #line 143 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                                        Write(Piranha.Resources.Template.PropertyPlaceholder);

            
            #line default
            #line hidden
WriteLiteral("\" /></div>\r\n            <button id=\"po_add\" class=\"btn right\">");


            
            #line 144 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
                                             Write(Piranha.Resources.Global.Add);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            <div class=\"clear\"></div>\r\n         </div>\r\n    </div>\r\n</" +
"div>\r\n");


            
            #line 149 "..\..\Areas\Manager\Views\Template\PostEdit.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
