#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/Partial/GroupList.cshtml")]
    public partial class GroupList : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.GroupListModel>
    {
        public GroupList()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
  
    Layout = "";


            
            #line default
            #line hidden

            
            #line 6 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
 foreach (var group in Model.Groups) {

            
            #line default
            #line hidden
WriteLiteral("<div class=\"half left\">\r\n    <p class=\"checkbox\">\r\n");


            
            #line 9 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
           var cbId = "Page_DisabledGroups_" + group.Name ; 

            
            #line default
            #line hidden
WriteLiteral("        <input type=\"checkbox\" id=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
                              Write(cbId);

            
            #line default
            #line hidden
WriteLiteral("\" name=\"Page.DisabledGroups\" value=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
                                                                       Write(group.Id);

            
            #line default
            #line hidden
WriteLiteral("\"\r\n            ");


            
            #line 11 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
        Write(Model.Page.DisabledGroups.Contains(group.Id) ? "checked=checked" : "");

            
            #line default
            #line hidden
WriteLiteral(" />\r\n        <label for=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
               Write(cbId);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 12 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
                      Write(group.Name);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n    </p>\r\n</div>\r\n");


            
            #line 15 "..\..\Areas\Manager\Views\Shared\Partial\GroupList.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
