#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Comment
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Comment/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<Piranha.Areas.Manager.Models.CommentEditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
  
    ViewBag.Title = @Piranha.Resources.Comment.EditTitleExisting;


            
            #line default
            #line hidden

DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 7 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 11 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                    Write(Url.Action("delete", new { id = Model.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 12 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                                                                                 Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                    Write(Url.Action("index", "comment"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 13 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                                                                  Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 14 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                    Write(Url.Action("edit", new { id = Model.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 14 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                                                                                Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n");


            
            #line 20 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
   Html.BeginForm() ; 

            
            #line default
            #line hidden

            
            #line 21 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 22 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
Write(Html.HiddenFor(m => m.AuthorName));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
Write(Html.HiddenFor(m => m.AuthorEmail));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_9\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 26 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                          Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 29 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
               Write(Html.LabelFor(m => m.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 31 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 32 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>");


            
            #line 34 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
               Write(Html.LabelFor(m => m.Status));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 36 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                   Write(Html.DropDownListFor(m => m.Status, Model.Statuses));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>");


            
            #line 38 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
               Write(Html.LabelFor(m => m.Body));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 40 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                   Write(Html.TextAreaFor(m => m.Body, new { @rows = 10 }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</d" +
"iv>\r\n<div class=\"grid_3\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2" +
">");


            
            #line 48 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                          Write(Piranha.Resources.Comment.Author);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 51 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
               Write(Html.LabelFor(m => m.AuthorName));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <p>");


            
            #line 52 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                  Write(Model.AuthorName);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                </li>\r\n                <li>");


            
            #line 54 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
               Write(Html.LabelFor(m => m.AuthorEmail));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <p><a href=\"mailto:");


            
            #line 55 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                                  Write(Model.AuthorEmail);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 55 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
                                                      Write(Model.AuthorEmail);

            
            #line default
            #line hidden
WriteLiteral("</a></p>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n<" +
"/div>\r\n");


            
            #line 61 "..\..\Areas\Manager\Views\Comment\Edit.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
