#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Comment
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Comment/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Piranha.Areas.Manager.Models.CommentListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
  
    ViewBag.Title = Piranha.Resources.Comment.ListTitle;


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"">
        $(document).ready(function () {
            // Setup list
            var options = {
                listClass:  'list-js',
                searchId: 'search',
                valueNames: ['title', 'author', 'status', 'created']
            };
            new List('list', options);
        });
    </script>
");


});


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n");


            
            #line 19 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a href=\"");


            
            #line 23 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                    Write(Url.Action("index"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 23 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                          Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <button class=\"search\" title=\"");


            
            #line 25 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                 Write(Piranha.Resources.Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 25 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                                                   Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <table id=\"list\" class=\"list\">\r\n        <thead>\r\n   " +
"         <tr>\r\n                <th><span class=\"sort asc\" data-sort=\"title\">");


            
            #line 34 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                        Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"status\">");


            
            #line 35 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                     Write(Piranha.Resources.Comment.Author);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"author\">");


            
            #line 36 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                     Write(Piranha.Resources.Global.Status);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"crea" +
"ted\">");


            
            #line 37 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"one\"></th>\r\n            </tr>\r\n        <" +
"/thead>\r\n        <tbody class=\"list-js\">\r\n");


            
            #line 42 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
             foreach (var comment in Model.Comments) {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td class=\"title\"><a href=\"");


            
            #line 44 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                      Write(Url.Action("edit", new { id = comment.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 44 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                                                    Write(comment.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td class=\"author\"><a href=\"mailto:");


            
            #line 45 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                              Write(comment.AuthorEmail);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 45 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                                                                    Write(comment.AuthorName);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td class=\"status\">");


            
            #line 46 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                              Write(comment.StatusName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"created\">");


            
            #line 47 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                               Write(comment.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"buttons\">\r\n                    <a href=\"");


            
            #line 49 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
                        Write(Url.Action("delete", new { id = comment.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Ta bort kommentaren\" class=\"icon delete\"></a></td>\r\n            </tr>\r\n");


            
            #line 51 "..\..\Areas\Manager\Views\Comment\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
