#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Comment
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Comment\List.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Comment/List.cshtml")]
    public partial class List : System.Web.Mvc.WebViewPage<List<Piranha.Entities.Comment>>
    {
        public List()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Comment\List.cshtml"
  
    Layout = "";


            
            #line default
            #line hidden
WriteLiteral("<table class=\"list\">\r\n    <tr>\r\n        <td><strong>");


            
            #line 8 "..\..\Areas\Manager\Views\Comment\List.cshtml"
               Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n        <td><strong>");


            
            #line 9 "..\..\Areas\Manager\Views\Comment\List.cshtml"
               Write(Piranha.Resources.Comment.Author);

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n        <td><strong>");


            
            #line 10 "..\..\Areas\Manager\Views\Comment\List.cshtml"
               Write(Piranha.Resources.Global.Status);

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n        <td class=\"date\"><strong>");


            
            #line 11 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                            Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</strong></td>\r\n    </tr>\r\n");


            
            #line 13 "..\..\Areas\Manager\Views\Comment\List.cshtml"
     foreach (var comment in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <tr>\r\n        <td><a class=\"btn-comment-expand\" href=\"#\" data-id=\"");


            
            #line 15 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                       Write(comment.Id);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 15 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                                    Write(comment.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n        <td><a href=\"mailto:");


            
            #line 16 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                       Write(comment.Author.Email);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 16 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                              Write(comment.Author.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n        <td>");


            
            #line 17 "..\..\Areas\Manager\Views\Comment\List.cshtml"
       Write(comment.StatusName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n        <td>");


            
            #line 18 "..\..\Areas\Manager\Views\Comment\List.cshtml"
       Write(comment.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    </tr>\r\n");



WriteLiteral("    <tr class=\"comment-detail\" style=\"display:none\" id=\"");


            
            #line 20 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                   Write(comment.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <td colspan=\"4\">\r\n            <p>");


            
            #line 22 "..\..\Areas\Manager\Views\Comment\List.cshtml"
          Write(comment.Body);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Comment\List.cshtml"
             if (User.HasAccess("ADMIN_COMMENT")) {

            
            #line default
            #line hidden
WriteLiteral("            <p class=\"comment-tools right\">\r\n                <a href=\"");


            
            #line 25 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                    Write(Url.Action("edit", "comment", new { @id = comment.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\">");


            
            #line 25 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                                                          Write(Piranha.Resources.Global.Edit);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                <a href=\"#\" data-id=\"");


            
            #line 26 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                Write(comment.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn comment-approve\">");


            
            #line 26 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                                         Write(Piranha.Resources.Comment.Approve);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                <a href=\"#\" data-id=\"");


            
            #line 27 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                Write(comment.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn comment-reject\">");


            
            #line 27 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                                        Write(Piranha.Resources.Comment.Reject);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                <a href=\"#\" class=\"btn comment-reply\" style=\"display:none\">" +
"");


            
            #line 28 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                                      Write(Piranha.Resources.Comment.Reply);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                <a href=\"#\" data-id=\"");


            
            #line 29 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                Write(comment.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn comment-delete\">");


            
            #line 29 "..\..\Areas\Manager\Views\Comment\List.cshtml"
                                                                        Write(Piranha.Resources.Global.Delete);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </p>\r\n");


            
            #line 31 "..\..\Areas\Manager\Views\Comment\List.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </td>\r\n    </tr>\r\n");


            
            #line 34 "..\..\Areas\Manager\Views\Comment\List.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</table>\r\n\r\n");


        }
    }
}
#pragma warning restore 1591
