#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Comment
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Comment/Settings.cshtml")]
    public partial class Settings : System.Web.Mvc.WebViewPage<Piranha.Areas.Manager.Models.CommentSettingsModel>
    {
        public Settings()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
  
    ViewBag.Title = @Piranha.Resources.Comment.SettingsTitle;


            
            #line default
            #line hidden

DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 7 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 11 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                    Write(Url.Action("settings"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 12 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                                                             Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n");


            
            #line 18 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
   Html.BeginForm() ; 

            
            #line default
            #line hidden
WriteLiteral("<div class=\"grid_12\">\r\n    <div class=\"box\">\r\n        <div class=\"title\">");


            
            #line 21 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                      Write(Html.CheckBoxFor(m => m.EnableAnonymous, new { @class = "right"}));

            
            #line default
            #line hidden
WriteLiteral("<h2>");


            
            #line 21 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                                                                                            Write(Piranha.Resources.Comment.AllowAnonymous);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n    </div>\r\n</div>\r\n<div class=\"grid_3\">\r\n    <div class=\"box\">\r\n   " +
"     <div class=\"title\"><h2>");


            
            #line 26 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                          Write(Piranha.Resources.Comment.Pages);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 29 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
               Write(Html.CheckBoxFor(m => m.EnablePages, new { @class = "right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <label>");


            
            #line 30 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                      Write(Piranha.Resources.Comment.Activate);

            
            #line default
            #line hidden
WriteLiteral("</label></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=" +
"\"grid_3\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 37 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                          Write(Piranha.Resources.Comment.Posts);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 40 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
               Write(Html.CheckBoxFor(m => m.EnablePosts, new { @class = "right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <label>");


            
            #line 41 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                      Write(Piranha.Resources.Comment.Activate);

            
            #line default
            #line hidden
WriteLiteral("</label></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=" +
"\"grid_3\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 48 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                          Write(Piranha.Resources.Comment.Media);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 51 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
               Write(Html.CheckBoxFor(m => m.EnableMedia, new { @class = "right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <label>");


            
            #line 52 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                      Write(Piranha.Resources.Comment.Activate);

            
            #line default
            #line hidden
WriteLiteral("</label></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n<div class=" +
"\"grid_3\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 59 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                          Write(Piranha.Resources.Comment.Uploads);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>");


            
            #line 62 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
               Write(Html.CheckBoxFor(m => m.EnableUploads, new { @class = "right" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <label>");


            
            #line 63 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
                      Write(Piranha.Resources.Comment.Activate);

            
            #line default
            #line hidden
WriteLiteral("</label></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n");


            
            #line 68 "..\..\Areas\Manager\Views\Comment\Settings.cshtml"
   Html.EndForm() ; 
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
