#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Content.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Content/Partial/ContentTree.cshtml")]
    public partial class ContentTree : System.Web.Mvc.WebViewPage<List<Piranha.Models.Content>>
    {
        public ContentTree()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
 foreach (var content in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <li class=\"");


            
            #line 4 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
           Write(content.ChildContent.Count > 0 ? (content.HasChild(ViewBag.Expanded) ? "expanded" : "collapsed") : "collapsed");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"buttons\">\r\n");


            
            #line 6 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
             if (content.IsFolder) {

            
            #line default
            #line hidden
WriteLiteral("            <a href=\"");


            
            #line 7 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                Write(Url.Action("insert", "content", new { id = content.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 7 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                                                                                  Write(Piranha.Resources.Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"icon add marg\"></a>\r\n");



WriteLiteral("            <a href=\"");


            
            #line 8 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                Write(Url.Action("insertfolder", "content", new { id = content.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 8 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                                                                                        Write(Piranha.Resources.Content.ToolbarAddFolder);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"icon add-folder marg\"></a>\r\n");


            
            #line 9 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 10 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
             if (content.ChildContent.Count == 0 && User.HasAccess("ADMIN_CONTENT_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <a href=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                Write(Url.Action("delete", "content", new { id = content.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                                                                                  Write(Piranha.Resources.Content.ListDelete);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n                class=\"icon delete ");


            
            #line 12 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                               Write(content.IsImage ? "media-image" : (content.IsFolder ? "media-folder" : ""));

            
            #line default
            #line hidden
WriteLiteral("\"></a>\r\n");


            
            #line 13 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </span>\r\n        <span class=\"date\">");


            
            #line 15 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                      Write(content.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <span class=\"date\">");


            
            #line 16 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                      Write(content.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden

            
            #line 16 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                                                                  WriteLiteral("</span>\r\n        <span class=\"title\">");

            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                             if (content.ChildContent.Count > 0) {
            
            #line default
            #line hidden
WriteLiteral("<span class=\"action\"></span>");


            
            #line 17 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                                                                                              }
            
            #line default
            #line hidden
WriteLiteral("<a href=\"");


            
            #line 17 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                                                                                                   Write(Url.Action("edit", "content", new { id = content.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <img class=\"thumb\" src=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                               Write(Url.GetThumbnailUrl(content.Id, 32));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
                                                                          Write(content.AlternateText);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n            ");


            
            #line 19 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
       Write(content.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"list-info\">\r\n                ");


            
            #line 21 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
           Write(Html.Raw(content.LastPublished == DateTime.MinValue ? "<span class=info-unpublished></span>" : (content.Updated > content.LastPublished ? "<span class=info-draft></span>" : "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div></a></span>\r\n");


            
            #line 23 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
         if (content.ChildContent.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("        <ul>\r\n            ");


            
            #line 25 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
       Write(Html.Partial("Partial/ContentTree", content.ChildContent));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n");


            
            #line 27 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </li>\r\n");


            
            #line 29 "..\..\Areas\Manager\Views\Content\Partial\ContentTree.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
