#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Post
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    using Piranha.Areas.Manager.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Post/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Piranha.Areas.Manager.Models.PostListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {




DefineSection("Head", () => {

WriteLiteral(@"
    <style type=""text/css"">
        .content .tabs {
            float: left;
            margin-left: 10px;
        }
        .content .tabs .selected {
            border: 0 none;
            padding: 10px 20px 6px;
        }
    </style>
    <script type=""text/javascript"">
        function addPost() {
");


            
            #line 17 "..\..\Areas\Manager\Views\Post\Index.cshtml"
             if (Model.ActiveTemplate == Guid.Empty) {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("floatBox.show(\'boxTemplates\');");

WriteLiteral("\r\n");


            
            #line 19 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                ");

WriteLiteral("$(\'form\').submit();");

WriteLiteral("\r\n");


            
            #line 21 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        }

        $(document).ready(function () {
            // Set the selected template id
            $("".templates"").click(function () {
                $(""#TemplateId"").val($(this).attr(""data-templateid""));
                $(""form"").submit();
            });

            // Notification before delete
            $("".delete"").click(function() {
                return confirm(""");


            
            #line 33 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                           Write(Piranha.Resources.Post.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral(@""") ;
            });

            // Setup post list
            var options = {
                listClass:  'list-js',
                searchId: 'search',
                valueNames: ['title', 'template', 'updated', 'created']
            };
            var postList = new List('list', options);
        });
    </script>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n");


            
            #line 47 "..\..\Areas\Manager\Views\Post\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a onclick=\"addPost()\" class=\"add\">");


            
            #line 51 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                              Write(Piranha.Resources.Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"\" class=\"refresh\">");


            
            #line 52 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                      Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            ");


            
            #line 53 "..\..\Areas\Manager\Views\Post\Index.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <button class=\"search\" title=\"");


            
            #line 55 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                 Write(Piranha.Resources.Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 55 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                   Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n");


            
            #line 61 "..\..\Areas\Manager\Views\Post\Index.cshtml"
 using (Html.BeginForm("insert", (string)ViewContext.RouteData.Values["Controller"])) {

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        ");


            
            #line 63 "..\..\Areas\Manager\Views\Post\Index.cshtml"
   Write(Html.Hidden("TemplateId", @Model.ActiveTemplate));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 64 "..\..\Areas\Manager\Views\Post\Index.cshtml"
         if (Model.ActiveTemplate != Guid.Empty) {

            
            #line default
            #line hidden
WriteLiteral("        ");


            
            #line 65 "..\..\Areas\Manager\Views\Post\Index.cshtml"
         Write(Html.Hidden("returl", Url.Action("template", "post", new { id = Model.ActiveTemplate})));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 66 "..\..\Areas\Manager\Views\Post\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");


            
            #line 68 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    if (Model.Templates.Count > 1) {

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <ul class=\"tabs\">\r\n            <li><a href=\"");


            
            #line 71 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                    Write(Url.Action("index", "post"));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 71 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                   Write(Model.ActiveTemplate == Guid.Empty ? "class=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">All</a></li>\r\n");


            
            #line 72 "..\..\Areas\Manager\Views\Post\Index.cshtml"
             foreach (var template in Model.Templates) {

            
            #line default
            #line hidden
WriteLiteral("            <li>\r\n                <a href=\"");


            
            #line 74 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                    Write(Url.Action("template", "post", new { @id = template.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 74 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                 Write(template.Id == Model.ActiveTemplate ? "class=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 74 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                                                                               Write(template.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </li>\r\n");


            
            #line 76 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n");


            
            #line 80 "..\..\Areas\Manager\Views\Post\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <table id=\"list\" class=\"list\">\r\n        <thead>\r\n            <tr>\r\n          " +
"      <th><span class=\"sort asc\" data-sort=\"title\">");


            
            #line 84 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                        Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"template\">");


            
            #line 85 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                       Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"upda" +
"ted\">");


            
            #line 86 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"crea" +
"ted\">");


            
            #line 87 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"one\"></th>\r\n            </tr>\r\n        <" +
"/thead>\r\n        <tbody class=\"list-js\">\r\n");


            
            #line 92 "..\..\Areas\Manager\Views\Post\Index.cshtml"
             foreach (var post in Model.Posts) {

            
            #line default
            #line hidden
WriteLiteral("            <tr");


            
            #line 93 "..\..\Areas\Manager\Views\Post\Index.cshtml"
           Write(post.Status == PostListModel.PostStatus.DRAFT || post.Status == PostListModel.PostStatus.UNPUBLISHED ? " class=draft" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <td class=\"title\">\r\n                    <a href=\"");


            
            #line 95 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                         Write(Model.ActiveTemplate == Guid.Empty ? 
                        Url.Action("edit", new { id = post.Id }) : 
                        Url.Action("edit", new { id = post.Id, returl = Url.Action("template", new { id = Model.ActiveTemplate}) }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    ");


            
            #line 98 "..\..\Areas\Manager\Views\Post\Index.cshtml"
               Write(post.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"list-info\">\r\n                        ");


            
            #line 100 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                   Write(Html.Raw(post.Status == PostListModel.PostStatus.UNPUBLISHED ? "<span class=info-unpublished></span>" : (post.Status == PostListModel.PostStatus.DRAFT ? "<span class=info-draft></span>" : "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 101 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                         if (post.NewComments > 0) {

            
            #line default
            #line hidden
WriteLiteral("                        <span class=\"notification\">");


            
            #line 102 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                              Write(post.NewComments);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 103 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </a></td>\r\n                <td class=" +
"\"template\">");


            
            #line 106 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                Write(post.TemplateName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"updated\">");


            
            #line 107 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                               Write(post.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"created\">");


            
            #line 108 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                               Write(post.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"buttons\">\r\n");


            
            #line 110 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                     if (User.HasAccess("ADMIN_POST_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("                    <a href=\"");


            
            #line 111 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                        Write(Url.Action("delete", new { id = post.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"Ta bort artikel\" class=\"icon delete\"></a>\r\n");


            
            #line 112 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n");


            
            #line 115 "..\..\Areas\Manager\Views\Post\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td colspan=" +
"\"5\"></td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n");


            
            #line 123 "..\..\Areas\Manager\Views\Post\Index.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


DefineSection("Foot", () => {

WriteLiteral("\r\n<div id=\"boxTemplates\" class=\"floatbox\">\r\n    <div class=\"bg\"></div>\r\n    <div " +
"class=\"box\">\r\n        <div class=\"title\"><a class=\"close-btn right\" data-id=\"box" +
"Templates\"></a><h2>");


            
            #line 130 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                Write(Piranha.Resources.Post.PopupTypeTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n");


            
            #line 132 "..\..\Areas\Manager\Views\Post\Index.cshtml"
         foreach (var template in Model.Templates) {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"templates ");


            
            #line 133 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                              Write(Model.Templates.Count > 6 ? "compressed" : "");

            
            #line default
            #line hidden
WriteLiteral(" left\" data-templateid=\"");


            
            #line 133 "..\..\Areas\Manager\Views\Post\Index.cshtml"
                                                                                                     Write(template.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <h3>");


            
            #line 134 "..\..\Areas\Manager\Views\Post\Index.cshtml"
               Write(template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                <div class=\"preview\" style=\"width:120px;height:120px;margi" +
"n:0 auto;\">\r\n                    ");


            
            #line 136 "..\..\Areas\Manager\Views\Post\Index.cshtml"
               Write(template.Preview.Html());

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <p>");


            
            #line 138 "..\..\Areas\Manager\Views\Post\Index.cshtml"
              Write(template.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n");


            
            #line 140 "..\..\Areas\Manager\Views\Post\Index.cshtml"
        } 

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n");


});


        }
    }
}
#pragma warning restore 1591
