#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Install
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Install\Update.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Install/Update.cshtml")]
    public partial class Update : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Update()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\Manager\Views\Install\Update.cshtml"
  
    ViewBag.Title = @Piranha.Resources.Account.UpdateTitle;
    Layout = "";

    var curr = Piranha.Models.SysParam.GetByName("SITE_VERSION");


            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta http-equiv=\"content-type\" content=\"tex" +
"t/html; charset=utf-8\"/>\r\n    <title>");


            
            #line 12 "..\..\Areas\Manager\Views\Install\Update.cshtml"
      Write(Piranha.Resources.Account.UpdateTitle);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n    <link href=\"");


            
            #line 14 "..\..\Areas\Manager\Views\Install\Update.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"icon\" type=\"image/x-icon\">\r\n    <link href=\"");


            
            #line 15 "..\..\Areas\Manager\Views\Install\Update.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"shortcut icon\" type=\"image/x-icon\"> \r\n    <link href=\"");


            
            #line 16 "..\..\Areas\Manager\Views\Install\Update.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/css/style.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                   Write(Href("~/res.ashx/areas/manager/content/js/ext/jquery-1.7.2.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 19 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                   Write(Href("~/res.ashx/areas/manager/content/js/jquery.manager.js"));

            
            #line default
            #line hidden
WriteLiteral(@"""></script>
    <script type=""text/javascript"">
        $(document).ready(function () {
            $("".message"").click(function () { $(this).fadeOut(""medium""); });

            if ($(""#sysMsg"").text() != """") {
                floatBox.show(""boxMessage"");
            }
            $(""#login"").focus();
        });
    </script>
</head>
<body>
    <div class=""container_12"">
        <div class=""grid_4 box login"">
            <div class=""title""><h2>");


            
            #line 34 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                              Write(Piranha.Resources.Account.UpdateTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <p>");


            
            #line 36 "..\..\Areas\Manager\Views\Install\Update.cshtml"
              Write(Html.Raw(String.Format(Piranha.Resources.Account.UpdateMessage, Piranha.Data.Database.InstalledVersion, Piranha.Data.Database.CurrentVersion)));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                <br />\r\n");


            
            #line 38 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                   Html.BeginForm("runupdate", "install") ; 

            
            #line default
            #line hidden
WriteLiteral("                <ul class=\"form\">\r\n                    <li><label>");


            
            #line 40 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                          Write(Piranha.Resources.Account.Username);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div class=\"input\"><input id=\"login\" name=\"logi" +
"n\" type=\"text\" /></div></li>\r\n                    <li><label>");


            
            #line 42 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                          Write(Piranha.Resources.Account.Password);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div class=\"input\"><input name=\"password\" type=" +
"\"password\" /></div></li>\r\n                <div class=\"separator\"></div>\r\n       " +
"         <br />\r\n                <button class=\"btn full big\" type=\"submit\">");


            
            #line 46 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                                                      Write(Piranha.Resources.Account.Update);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 47 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                   Html.EndForm() ; 

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"clear\"></div>\r\n            </div>\r\n        </div>\r\n  " +
"  </div>\r\n    <div id=\"boxMessage\" class=\"floatbox\">\r\n        <div class=\"bg\"></" +
"div>\r\n        <div class=\"box\">\r\n            <div class=\"title\"><h2>");


            
            #line 55 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                              Write(Piranha.Resources.Global.PopupMessageTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\" style=\"width: 360px;min-height:60px;t" +
"ext-align:center\">\r\n                <p id=\"sysMsg\">");


            
            #line 57 "..\..\Areas\Manager\Views\Install\Update.cshtml"
                          Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
