#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Dialog
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Dialog\Link.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Dialog/Link.cshtml")]
    public partial class Link : System.Web.Mvc.WebViewPage<Piranha.Areas.Manager.Models.LinkDialogModel>
    {
        public Link()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Dialog\Link.cshtml"
  
    Layout = "";


            
            #line default
            #line hidden
WriteLiteral(@"<div class=""title"">
    <ul class=""box-tabs"">
        <li class=""selected""><a class=""btn-link-page"" href=""#link-page"">Pages</a></li>
        <li><a class=""btn-link-media"" href=""#link-media"">Media</a></li>
    </ul>
    <a class=""close-btn right"" data-id=""boxLink""></a>
    <div class=""clear""></div>
</div>
<div id=""link-page"" class=""inner link-page"">
    <ul class=""sitemap"">
        ");


            
            #line 16 "..\..\Areas\Manager\Views\Dialog\Link.cshtml"
   Write(Html.Partial("Partial/DialogSiteTree", Model.Pages));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </ul>\r\n    <div class=\"clear\"></div>\r\n    <div class=\"loader\"></div>\r\n</div" +
">\r\n<div id=\"link-media\" class=\"inner link-media hidden\">\r\n    Yo my man\r\n</div>\r" +
"\n");


        }
    }
}
#pragma warning restore 1591
