#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.SiteTree
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/SiteTree/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Piranha.Areas.Manager.Models.SiteTreeListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
  
    ViewBag.Title = Piranha.Resources.SiteTree.ListTitle;


            
            #line default
            #line hidden

DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        var deletemsg = \'");


            
            #line 8 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                    Write(Piranha.Resources.SiteTree.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral(@"';

        $(document).ready(function () {
            // Setup list
            var options = {
                listClass:  'list-js',
                searchId: 'search',
                valueNames: ['title', 'description', 'updated', 'created']
            };
            new List('list', options);

            $('.list .delete').click(function () {
                return confirm(deletemsg);
            });
        });
    </script>
");


});


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n");


            
            #line 25 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a href=\"");


            
            #line 29 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                    Write(Url.Action("edit", "sitetree"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"add\">");


            
            #line 29 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                                 Write(Piranha.Resources.Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 30 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                    Write(Url.Action("index"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 30 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                          Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            ");


            
            #line 31 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <button class=\"search\" title=\"");


            
            #line 33 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                 Write(Piranha.Resources.Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 33 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                                                   Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <table id=\"list\" class=\"list\">\r\n        <thead>\r\n   " +
"         <tr>\r\n                <th><span class=\"sort asc\" data-sort=\"title\">");


            
            #line 42 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                        Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th><span class=\"sort\" data-sort=\"description\">");


            
            #line 43 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                          Write(Piranha.Resources.Global.Description);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"upda" +
"ted\">");


            
            #line 44 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"crea" +
"ted\">");


            
            #line 45 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"one\"></th>\r\n            </tr>\r\n        <" +
"/thead>\r\n        <tbody class=\"list-js\">\r\n");


            
            #line 50 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
             foreach (var site in Model.Sites) {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td class=\"title\"><a href=\"");


            
            #line 52 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                      Write(Url.Action("edit", new { id = site.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 52 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                                                                 Write(site.Name);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                <td class=\"description\">");


            
            #line 53 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                                   Write(site.Description);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"updated\">");


            
            #line 54 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                               Write(site.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"created\">");


            
            #line 55 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                               Write(site.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"buttons\">\r\n");


            
            #line 57 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                     if (Model.CanDeleteSite[site.Id] && site.Id != Piranha.Config.DefaultSiteTreeId) {

            
            #line default
            #line hidden
WriteLiteral("                    <a href=\"");


            
            #line 58 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                        Write(Url.Action("delete", new { id = site.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"\" class=\"icon delete\"></a>\r\n");


            
            #line 59 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n");


            
            #line 62 "..\..\Areas\Manager\Views\SiteTree\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
