#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Account
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Account\Index.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Account/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Index()
        {
        }
        public override void Execute()
        {


            
            #line 2 "..\..\Areas\Manager\Views\Account\Index.cshtml"
  
    ViewBag.Title = @Piranha.Resources.Account.Title;
    Layout = "";


            
            #line default
            #line hidden
WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta http-equiv=\"content-type\" content=\"tex" +
"t/html; charset=utf-8\"/>\r\n    <title>");


            
            #line 10 "..\..\Areas\Manager\Views\Account\Index.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(@"</title>

    <link href=""~/res.ashx/areas/manager/content/img/icon.ico"" rel=""icon"" type=""image/x-icon"">
    <link href=""~/res.ashx/areas/manager/content/img/icon.ico"" rel=""shortcut icon"" type=""image/x-icon""> 
    <link href=""~/res.ashx/areas/manager/content/css/style.min.css"" rel=""stylesheet"" type=""text/css""/>

    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/ext/jquery-1.7.2.min.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.manager.js""></script>
    <script type=""text/javascript"">
        $(document).ready(function () {
            $("".message"").click(function () { $(this).fadeOut(""medium""); });

            if ($(""#sysMsg"").text() != """") {
                floatBox.show(""boxMessage"");
            }

            $(""#login"").focus();
        });
    </script>
</head>
<body>
    <div class=""container_12"">
        <div class=""grid_4 box login"">
            <div class=""title""><small>");


            
            #line 33 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                  Write("v" + ViewBag.Version);

            
            #line default
            #line hidden
WriteLiteral("</small><h2>");


            
            #line 33 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                                                     Write(Piranha.Resources.Account.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n");


            
            #line 35 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                   Html.BeginForm("login", "account") ; 

            
            #line default
            #line hidden
WriteLiteral("                ");


            
            #line 36 "..\..\Areas\Manager\Views\Account\Index.cshtml"
           Write(Html.Hidden("returnaction", "index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 37 "..\..\Areas\Manager\Views\Account\Index.cshtml"
           Write(Html.Hidden("returncontroller", "page"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <ul class=\"form\">\r\n                    <li><label>");


            
            #line 39 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                          Write(Piranha.Resources.Account.Username);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div class=\"input\"><input id=\"login\" name=\"logi" +
"n\" type=\"text\" /></div></li>\r\n                    <li><label>");


            
            #line 41 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                          Write(Piranha.Resources.Account.Password);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <div class=\"input\"><input name=\"password\" type=" +
"\"password\" /></div></li>\r\n                </ul>\r\n                <button type=\"s" +
"ubmit\" class=\"btn right\">");


            
            #line 44 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                                                   Write(Piranha.Resources.Account.Login);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 45 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                   Html.EndForm() ; 

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"clear\"></div>\r\n            </div>\r\n        </div>\r\n  " +
"  </div>\r\n    <div id=\"boxMessage\" class=\"floatbox\">\r\n        <div class=\"bg\"></" +
"div>\r\n        <div class=\"box\">\r\n            <div class=\"title\"><h2>");


            
            #line 53 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                              Write(Piranha.Resources.Global.PopupMessageTitle);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\" style=\"width: 360px;min-height:60px;t" +
"ext-align:center\">\r\n                <p id=\"sysMsg\">");


            
            #line 55 "..\..\Areas\Manager\Views\Account\Index.cshtml"
                          Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
