#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page.Partial
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Partial/SiteTree.cshtml")]
    public partial class SiteTree : System.Web.Mvc.WebViewPage<List<Piranha.Models.Sitemap>>
    {
        public SiteTree()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
 foreach (var page in Model) {

            
            #line default
            #line hidden
WriteLiteral("    <li id=\"");


            
            #line 4 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
       Write(page.Id);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"");


            
            #line 4 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                         Write(page.Pages.Count > 0 ? (page.Level <= ViewBag.Levels || page.HasChild(ViewBag.Expanded) ? "expanded" : "collapsed") : "");

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 4 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                                                                                                                     Write(page.Updated > page.LastPublished ? "draft" : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"buttons\">\r\n            <button class=\"icon add-after mar" +
"g\" title=\"");


            
            #line 6 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                  Write(Piranha.Resources.Page.ListAddAfter);

            
            #line default
            #line hidden
WriteLiteral("\" onclick=\"return preSubmit(\'");


            
            #line 6 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                                                                                   Write(page.ParentId);

            
            #line default
            #line hidden
WriteLiteral("\', ");


            
            #line 6 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                                                                                                     Write(page.Seqno + 1);

            
            #line default
            #line hidden
WriteLiteral(")\" type=\"submit\"></button>\r\n            <button class=\"icon add-below marg\" title" +
"=\"");


            
            #line 7 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                  Write(Piranha.Resources.Page.ListAddBelow);

            
            #line default
            #line hidden
WriteLiteral("\" onclick=\"return preSubmit(\'");


            
            #line 7 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                                                                                   Write(page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', 1)\" type=\"submit\"></button>\r\n");


            
            #line 8 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
             if (page.Pages.Count == 0 && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <a href=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                Write(Url.Action("delete", "page", new { id = page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                                            Write(Piranha.Resources.Page.ListDelete);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"icon delete\"></a>\r\n");


            
            #line 10 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </span>\r\n        <span class=\"date\">");


            
            #line 12 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                      Write(page.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <span class=\"date\">");


            
            #line 13 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                      Write(page.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <span class=\"type\">");


            
            #line 14 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                      Write(page.TemplateName);

            
            #line default
            #line hidden

            
            #line 14 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                             WriteLiteral("</span>\r\n        <span class=\"title\">");

            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                             if (page.Pages.Count > 0) {
            
            #line default
            #line hidden
WriteLiteral("<span class=\"action\"></span>");


            
            #line 15 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                                                    }
            
            #line default
            #line hidden
WriteLiteral("<a href=\"");


            
            #line 15 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
                                                                                         Write(Url.Action("edit", "page", new { id = page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 16 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
        Write(!String.IsNullOrEmpty(page.NavigationTitle) ? page.NavigationTitle : page.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"list-info\">\r\n                ");


            
            #line 18 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
           Write(Html.Raw(page.LastPublished == DateTime.MinValue ? "<span class=info-unpublished></span>" : (page.Updated > page.LastPublished ? "<span class=info-draft></span>" : "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                ");


            
            #line 19 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
           Write(Html.Raw(page.OriginalId != Guid.Empty ? "<span class=info-copy></span>" : ""));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div></a></span>\r\n");


            
            #line 21 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
         if (page.Pages.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("        <ul>\r\n            ");


            
            #line 23 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
       Write(Html.Partial("Partial/SiteTree", page.Pages));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n");


            
            #line 25 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </li>\r\n");


            
            #line 27 "..\..\Areas\Manager\Views\Page\Partial\SiteTree.cshtml"
}

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
