#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/Group.cshtml")]
    public partial class Group : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.SettingModels.GroupEditModel>
    {
        public Group()
        {
        }
        public override void Execute()
        {



DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        $(document).ready(function () {\r\n " +
"           $(\'#Group_Name\').focus();\r\n        });\r\n    </script>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 11 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 15 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 16 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                    Write(Url.Action("deletegroup", new { id = Model.Group.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 16 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 17 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                    Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 17 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                                                           Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                    Write(Url.Action("group", new { id = Model.Group.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 18 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                                                                                       Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n");


            
            #line 24 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
   Html.BeginForm() ; 

            
            #line default
            #line hidden

            
            #line 25 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
Write(Html.HiddenFor(m => m.Group.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 26 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
Write(Html.HiddenFor(m => m.Group.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 27 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
Write(Html.HiddenFor(m => m.Group.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_9\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 30 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                          Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 34 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
               Write(Html.LabelFor(m => m.Group.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 36 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                   Write(Html.TextBoxFor(m => m.Group.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 37 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
               Write(Html.ValidationMessageFor(m => m.Group.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 40 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
               Write(Html.LabelFor(m => m.Group.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 42 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                   Write(Html.TextAreaFor(m => m.Group.Description, 
                            new { @rows = 3, @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 46 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
               Write(Html.LabelFor(m => m.Group.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 48 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                   Write(Html.DropDownListFor(m => m.Group.ParentId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 49 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
               Write(Html.ValidationMessageFor(m => m.Group.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n</div>\r\n<" +
"div class=\"grid_3\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 57 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                          Write(Piranha.Resources.Settings.GroupMembers);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n");


            
            #line 59 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
             if (!Model.Group.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("            <ul class=\"list\">\r\n");


            
            #line 61 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                 foreach (var user in Model.Members) {

            
            #line default
            #line hidden
WriteLiteral("                <li><a href=\"");


            
            #line 62 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                        Write(Url.Action("user", new { id = user.Id }));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 62 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                                                                    Write(!String.IsNullOrEmpty(user.Name) ? user.Name : user.Login);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 63 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </ul>\r\n");


            
            #line 65 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("                <p><em>");


            
            #line 66 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
                  Write(Piranha.Resources.Settings.GroupMembersNew);

            
            #line default
            #line hidden
WriteLiteral("</em></p>\r\n");


            
            #line 67 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</div>\r\n");


            
            #line 71 "..\..\Areas\Manager\Views\Settings\Group.cshtml"
   Html.EndForm() ; 

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
