#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Settings
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Settings/Param.cshtml")]
    public partial class Param : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.SettingModels.ParamEditModel>
    {
        public Param()
        {
        }
        public override void Execute()
        {



DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        $(document).ready(function () {\r\n " +
"           $(\'#Param_Name\').focus();\r\n        });\r\n    </script>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 11 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 15 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 16 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
             if (!Model.Param.IsLocked) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 17 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                    Write(Url.Action("deleteparam", new { id = Model.Param.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 17 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 18 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 19 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                    Write(Url.Action("paramlist"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 19 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                           Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 20 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                    Write(Url.Action("param", new { id = Model.Param.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 20 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                       Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n");


            
            #line 26 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
   Html.BeginForm() ; 

            
            #line default
            #line hidden

            
            #line 27 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 28 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 29 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.IsLocked));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 30 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
Write(Html.HiddenFor(m => m.Param.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>In" +
"formation</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">" +
"\r\n                <li>\r\n                    ");


            
            #line 37 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.LabelFor(m => m.Param.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n");


            
            #line 39 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                         if (!Model.Param.IsLocked) {
                            
            
            #line default
            #line hidden
            
            #line 40 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Name));

            
            #line default
            #line hidden
            
            #line 40 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                               
                        } else {
                            
            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Name, new { @disabled = "disabled" }));

            
            #line default
            #line hidden
            
            #line 42 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                               
                            
            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.HiddenFor(m => m.Param.Name));

            
            #line default
            #line hidden
            
            #line 43 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                              
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                    ");


            
            #line 46 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.ValidationMessageFor(m => m.Param.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 49 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.LabelFor(m => m.Param.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n");


            
            #line 51 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                         if (Model.Param.Name != "SITE_VERSION") {
                            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Value));

            
            #line default
            #line hidden
            
            #line 52 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                
                        } else {
                            
            
            #line default
            #line hidden
            
            #line 54 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextBoxFor(m => m.Param.Value, new { @disabled = "disabled" }));

            
            #line default
            #line hidden
            
            #line 54 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                                
                            
            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.HiddenFor(m => m.Param.Value));

            
            #line default
            #line hidden
            
            #line 55 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                               
                        } 

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </li>\r\n                <li>\r\n        " +
"            ");


            
            #line 60 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
               Write(Html.LabelFor(m => m.Param.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n");


            
            #line 62 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                         if (!Model.Param.IsLocked) {
                            
            
            #line default
            #line hidden
            
            #line 63 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextAreaFor(m => m.Param.Description, 
                                new { @rows = 3, @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
            
            #line 64 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                                    
                        } else {
                            
            
            #line default
            #line hidden
            
            #line 66 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.TextAreaFor(m => m.Param.Description, 
                                new { @rows = 3, @disabled = "disabled", @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
            
            #line 67 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                                                                            
                            
            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                       Write(Html.HiddenFor(m => m.Param.Description));

            
            #line default
            #line hidden
            
            #line 68 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
                                                                     
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n                </li>\r\n            </ul>\r\n        </d" +
"iv>\r\n    </div>\r\n</div>\r\n");


            
            #line 76 "..\..\Areas\Manager\Views\Settings\Param.cshtml"
   Html.EndForm() ; 

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
