#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Extensions.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Extensions/EditorTemplates/Attachment.cshtml")]
    public partial class Attachment : System.Web.Mvc.WebViewPage<Piranha.Extend.Regions.AttachmentRegion.Attachment>
    {
        public Attachment()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
  
    Layout = "";


            
            #line default
            #line hidden
WriteLiteral("<tr>\r\n    <td>\r\n        ");


            
            #line 8 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 9 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 10 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 11 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n        ");


            
            #line 12 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Html.HiddenFor(m => m.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <img src=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
             Write(Url.GetThumbnailUrl((Guid)Model.Id, 50));

            
            #line default
            #line hidden
WriteLiteral("\" /></td>\r\n    <td><a href=\"");


            
            #line 14 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
            Write(Url.Action("edit", "content", new { @id = Model.Id, @returl = Url.Action("edit", "page") }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        ");


            
            #line 15 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"list-info\">\r\n            ");


            
            #line 17 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
       Write(Html.Raw(Model.LastPublished == DateTime.MinValue ? "<span class=info-unpublished></span>" : 
                (Model.Updated > Model.LastPublished ? "<span class=info-draft></span>" : "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </a></td>\r\n    <td>");


            
            #line 21 "..\..\Areas\Manager\Views\Extensions\EditorTemplates\Attachment.cshtml"
   Write(Model.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n    <td class=\"buttons three\">\r\n        <a class=\"icon up marg\"></a>\r\n    " +
"    <a class=\"icon down marg\"></a>\r\n        <a class=\"icon delete\"></a></td>\r\n</" +
"tr>\r\n");


        }
    }
}
#pragma warning restore 1591
