#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 1 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/_Layout.cshtml")]
    public partial class Layout : System.Web.Mvc.WebViewPage<dynamic>
    {
        public Layout()
        {
        }
        public override void Execute()
        {

WriteLiteral("<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <meta http-equiv=\"content-type\" content=\"tex" +
"t/html; charset=utf-8\"/>\r\n    <meta name=\"viewport\" content=\"width=device-width," +
" initial-scale=1.0, maximum-scale=1.0\">\r\n    <title>");


            
            #line 7 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</title>\r\n\r\n    <link href=\"");


            
            #line 9 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"icon\" type=\"image/x-icon\">\r\n    <link href=\"");


            
            #line 10 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/img/icon.ico"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"shortcut icon\" type=\"image/x-icon\"> \r\n    <link href=\"");


            
            #line 11 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/css/ext/chosen.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n    <link href=\"");


            
            #line 12 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/css/ext/jquery-ui-1.9.2.custom.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" />\r\n    <link href=\"");


            
            #line 13 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Href("~/res.ashx/areas/manager/content/css/style.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");


            
            #line 14 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
     if (File.Exists(Server.MapPath("~/areas/manager/content/css/style.css"))) {

            
            #line default
            #line hidden
WriteLiteral("    <link href=\"");


            
            #line 15 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Href("~/areas/manager/content/css/style.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");


            
            #line 16 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    \r\n    <script type=\"text/javascript\" src=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                   Write(Href("~/res.ashx/areas/manager/content/js/ext/jquery-1.7.2.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 19 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                   Write(Href("~/res.ashx/areas/manager/content/js/jquery.manager.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 20 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                   Write(Href("~/res.ashx/areas/manager/content/js/ext/chosen.jquery.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n    <script type=\"text/javascript\">\r\n        var siteroot = \"");


            
            #line 22 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                   Write(Url.Content("~/"));

            
            #line default
            #line hidden
WriteLiteral("\";\r\n        var apikey = \"");


            
            #line 23 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                 Write(Html.APIKey("FE868D4F-797C-4E60-B876-64E6FC2424AA"));

            
            #line default
            #line hidden
WriteLiteral(@""";
        siteroot += !siteroot.endsWith(""/"") ? ""/"" : """";

        $(document).ready(function () {
            $("".message"").click(function () { $(this).fadeOut(""medium""); });

            $("".chzn-select"").chosen().trigger(""liszt:updated"");
        });
    </script>
");


            
            #line 32 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
     if (!String.IsNullOrEmpty(ViewBag.Message)) {

            
            #line default
            #line hidden
WriteLiteral("    <script type=\"text/javascript\">\r\n        setTimeout(function () {\r\n          " +
"  $(\".sys-message\").slideUp();\r\n        }, 2000);\r\n    </script>\r\n");


            
            #line 38 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 39 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("Head", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</head>\r\n<body>\r\n    <div class=\"top\">\r\n        <div class=\"container_12\">\r\n   " +
"         <div class=\"grid_12 header\">\r\n                <a class=\"home\" href=\"");


            
            #line 45 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                 Write(Url.Action("index", "page"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <img src=\"");


            
            #line 46 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                         Write(Href("~/res.ashx/areas/manager/content/img/logo.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"Piranha CMS\" /></a>\r\n                <div class=\"site-title\">\r\n           " +
"         <span>");


            
            #line 48 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                     Write(Piranha.WebPages.WebPiranha.CurrentSite.MetaTitle);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                    <a class=\"public-site\" target=\"preview\" href=\"");


            
            #line 49 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                                             Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        ");


            
            #line 50 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                   Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                </div>\r\n                ");


            
            #line 52 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(Html.Partial("Partial/Menu"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <div class=\"title\">\r\n      " +
"  <div class=\"container_12\">\r\n            <div class=\"grid_12\"><h1>");


            
            #line 58 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral("</h1></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"body\">\r\n        <div cla" +
"ss=\"container_12\">\r\n            <div class=\"grid_12 toolbar-container\">\r\n       " +
"         ");


            
            #line 64 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(RenderSection("Toolbar", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 66 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
             if (!String.IsNullOrEmpty(ViewBag.Message)) {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"grid_12 sys-message\">\r\n                <div class=\"box");


            
            #line 68 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                           Write(!String.IsNullOrEmpty(ViewBag.MessageCss) ? " " + ViewBag.MessageCss : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <div class=\"inner\">\r\n                        <div class=\"" +
"ico\"></div><p>");


            
            #line 70 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
                                             Write(ViewBag.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");


            
            #line 74 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"content left\">\r\n                ");


            
            #line 76 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>
        </div>
    </div>
    <div id=""boxSysMsg"" class=""floatbox"">
        <div class=""bg""></div>
        <div class=""box"">
            <div class=""title""><h2 id=""SysMsgTitle""></h2></div>
            <div class=""inner"">
                <p id=""SysMsgBody""></p>
            </div>
        </div>
    </div>
    <div id=""boxDialog"" class=""floatbox"">
        <div class=""bg"" style=""background-color: transparent""></div>
        <div class=""box"" style=""min-width: 510px;min-height:260px;"">
        </div>
    </div>
    ");


            
            #line 94 "..\..\Areas\Manager\Views\Shared\_Layout.cshtml"
Write(RenderSection("Foot", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
