#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Shared.EditorTemplates
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Shared/EditorTemplates/RegionTemplate.cshtml")]
    public partial class RegionTemplate : System.Web.Mvc.WebViewPage<Piranha.Models.RegionTemplate>
    {
        public RegionTemplate()
        {
        }
        public override void Execute()
        {


WriteLiteral("<tr>\r\n    <td class=\"form\">\r\n        <span>");


            
            #line 5 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
         Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <div class=\"input hidden\">\r\n            ");


            
            #line 7 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.TextBoxFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        ");


            
            #line 8 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
   Write(Html.ValidationMessageFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </td>\r\n    <td class=\"form\">\r\n        <span>");


            
            #line 11 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
         Write(Model.InternalId);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <div class=\"input hidden\">\r\n            ");


            
            #line 13 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.TextBoxFor(m => m.InternalId));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        <div style=\"position: relative\">\r\n            ");


            
            #line 15 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.ValidationMessageFor(m => m.InternalId));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n    </td>\r\n    <td>\r\n        <span class=\"readonly\">");


            
            #line 18 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
                          Write(Piranha.Extend.ExtensionManager.Current.GetNameByType(Model.Type));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n    </td>\r\n    <td class=\"buttons four\">\r\n        <a class=\"icon up marg" +
"\"></a>\r\n        <a class=\"icon down marg\"></a>\r\n        <a class=\"icon edit marg" +
"\"></a>\r\n        <a class=\"icon delete\"></a>\r\n        <div class=\"hidden\">\r\n     " +
"       ");


            
            #line 26 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 27 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.HiddenFor(m => m.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 28 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.HiddenFor(m => m.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 29 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.HiddenFor(m => m.Seqno, new { @class = "region-seqno" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 30 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.HiddenFor(m => m.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 31 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.HiddenFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 32 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
             if (!Model.IsNew) {
            
            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
       Write(Html.HiddenFor(m => m.Created));

            
            #line default
            #line hidden
            
            #line 33 "..\..\Areas\Manager\Views\Shared\EditorTemplates\RegionTemplate.cshtml"
                                           
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </td> \r\n</tr>\r\n");


        }
    }
}
#pragma warning restore 1591
