#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Extend;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Models.Manager.PageModels;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.EditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {





DefineSection("Head", () => {

WriteLiteral(@"
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.form.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.regions.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.attachment.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.media.dialog.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/jquery.comments.js""></script>
    <script type=""text/javascript"" src=""~/res.ashx/areas/manager/content/js/ext/jquery.equalheights.js""></script>
    ");


            
            #line 12 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("~/Areas/Manager/Views/Shared/Partial/TinyMCE.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n    \t\tvar folderId = \"\";\r\n    \t\tvar delete" +
"msg = \"");


            
            #line 15 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Piranha.Resources.Page.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n        $(document).ready(function () {\r\n            // UI Stuff\r\n         " +
"   $(\"#Page_Title\").focus();\r\n            $(\'.first-row .box\').equalHeights();\r\n" +
"\r\n");


            
            #line 22 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Action == EditModel.ActionType.ATTACHMENTS) {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral("\r\n            $(\'#btn_attachments\').click();\r\n            ");

WriteLiteral("\r\n");


            
            #line 26 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"
            $(""#Page_ParentId"").change(function () {
                var page_id = $(""#Page_Id"").val();
                var page_parentid = $(""#org_parentid"").val();
                var page_seqno = $(""#Page_Seqno"").val();
                var parentid = $(""#Page_ParentId"").val();
                var site_tree = $(""#Page_SiteTreeInternalId"").val();

                $.get(""");


            
            #line 35 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("siblings"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&page_parentid="" + page_parentid + ""&page_seqno="" + page_seqno + ""&parentid="" + parentid + ""&site_tree="" + site_tree, function (data) {
                    $(""#div-seqno"").html(data);
                });
            });

            $('#Page_GroupId').change(function() {
                var page_id = $(""#Page_Id"").val();
                var group_id = $(this).val();

                $.get(""");


            
            #line 44 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                  Write(Url.Action("grouplist"));

            
            #line default
            #line hidden
WriteLiteral(@"?page_id="" + page_id + ""&group_id="" + group_id, function(data) {
                    $(""#disable-groups"").html(data);
                });
            });

            $('#btnMove').click(function () {
                $('#placement-edit').slideToggle('fast');
                $(this).toggleClass('active');
                return false;
            });

            new piranha.comment('");


            
            #line 55 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            Write(Model.Page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', \'comment-notification\', \'pnl-comments .inner\');\r\n            \r\n            new" +
" piranha.media(\'btn_attach\', \'boxContent\', function (a) {\r\n                // St" +
"ore folder id so we can open the same folder next time.\r\n                folderI" +
"d = a.ParentId;\r\n\r\n                // Add the attachment\r\n                $(\"#tb" +
"l-attachments\").append(\r\n                    \'<tr data-id=\"\' + a.Id + \'\">\' +\r\n  " +
"                      \'<td><img src=\"\' + a.ThumbnailUrl + \'/50\" /></td>\' +\r\n    " +
"                    \'<td>\' + a.DisplayName + \'</td>\' +\r\n                        " +
"\'<td>\' + a.Type + \'</td>\' +\r\n                        \'<td class=\"buttons three\">" +
"\' +\r\n                            \'<a class=\"icon up marg\"></a>\' +\r\n             " +
"               \'<a class=\"icon down marg\"></a>\' +\r\n                            \'" +
"<a class=\"icon delete\"></a></td>\' +\r\n                    \'</tr>\');\r\n            " +
"});\r\n\r\n            $(\".delete\").click(function () {\r\n            \treturn confirm" +
"(deletemsg);\r\n            });\r\n        });\r\n\r\n        //\r\n        // Hides all e" +
"ditors on the page. This callback is called from jquery.attachments.js\r\n        " +
"//\r\n        function hideEditors() {\r\n            $(\"#pageregions .input, #globa" +
"lregions .input\").hide();\r\n            $(\"#regionbuttons button\").removeClass(\"a" +
"ctive\");\r\n            $(\"#attachments\").hide();\r\n\r\n            $(\"#regions .regi" +
"on-body\").hide();\r\n            $(\"#regionbuttons button\").removeClass(\"active\");" +
"\r\n            $(\"#attachments\").hide();\r\n        }\r\n\r\n        //\r\n        // Thi" +
"s callback is called from jquery.attachments.js before form submit.\r\n        //\r" +
"\n        function addAttachmentData(index, val) {\r\n            $(\"#attachment_da" +
"ta\").append(\r\n                    \'<input id=\"Page_Attachments_\' + index +\r\n    " +
"                \'_\" name=\"Page.Attachments[\' + index +\r\n                    \']\" " +
"type=\"hidden\" value=\"\' + $(val).attr(\"data-id\") + \'\" />\');\r\n        }\r\n    </scr" +
"ipt>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 105 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 109 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSaveDraft);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 110 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 111 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden

            
            #line 111 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                             Write(Url.GetPermalink(Model.Page.Permalink, true));

            
            #line default
            #line hidden
WriteLiteral("\" target=\"preview\" class=\"preview\">");


            
            #line 111 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Piranha.Resources.Global.ToolbarPreview);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 112 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 113 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a class=\"publish\">");


            
            #line 114 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Model.Page.Published == DateTime.MinValue ? Piranha.Resources.Global.ToolbarPublish : Piranha.Resources.Global.ToolbarUpdate);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 115 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 116 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 117 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(Url.Action("unpublish", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"unpublish\">");


            
            #line 117 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                            Write(Piranha.Resources.Global.ToolbarUnpublish);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 118 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 119 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (Model.Page.Published > DateTime.MinValue && Model.Page.Updated > Model.Page.LastPublished) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(Url.Action("revert", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"revert\">");


            
            #line 120 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarRevert);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 121 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 122 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (!Model.Page.IsNew && Model.CanDelete && !Model.IsSite && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 123 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(Url.Action("delete", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 123 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                      Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 124 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 125 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
             if (String.IsNullOrEmpty(ViewBag.ReturnUrl)) {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 126 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(Url.Action("index", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 126 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                   Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 127 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 128 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(ViewBag.ReturnUrl);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 128 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 129 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 130 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                    Write(Url.Action("edit", new { id = Model.Page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 130 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                     Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            ");


            
            #line 131 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n");


});

WriteLiteral("\r\n\r\n");


            
            #line 138 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.BeginForm("edit", (string)ViewContext.RouteData.Values["Controller"]) ; 

            
            #line default
            #line hidden
WriteLiteral("<div>\r\n    ");


            
            #line 140 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 141 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 142 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.SiteTreeInternalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 143 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.OriginalId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 144 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 145 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 146 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 147 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.TemplateId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 148 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 149 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 150 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 151 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Updated));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 152 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Published));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 153 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.LastPublished));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 154 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 155 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 156 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.NamespaceId));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 157 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n    ");


            
            #line 158 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 159 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (Model.IsSite) {
    
            
            #line default
            #line hidden
            
            #line 160 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Title));

            
            #line default
            #line hidden
            
            #line 160 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 161 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
            
            #line 161 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 162 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
            
            #line 162 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      
    
            
            #line default
            #line hidden
            
            #line 163 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
            
            #line 163 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                          
    }

            
            #line default
            #line hidden

            
            #line 165 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Application.Current.IsMvc) {
    
            
            #line default
            #line hidden
            
            #line 166 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.HiddenFor(m => m.Page.PageView));

            
            #line default
            #line hidden
            
            #line 166 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                         
    }

            
            #line default
            #line hidden
WriteLiteral("    ");


            
            #line 168 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
Write(Html.Hidden("returl", (string)ViewBag.ReturnUrl));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <input type=\"hidden\" id=\"draft\" name=\"draft\" value=\"true\" />\r\n    <input ty" +
"pe=\"hidden\" id=\"org_parentid\" value=\"");


            
            #line 170 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             Write(Model.Page.ParentId);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n</div>\r\n<div class=\"first-row\">\r\n    <div class=\"");


            
            #line 173 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
            Write(!String.IsNullOrEmpty(Model.Template.Preview.ToString()) ? "grid_9" : "grid_12");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <div class=\"box\">\r\n            <div class=\"title\"><h2>");


            
            #line 175 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                              Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n");


            
            #line 177 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                 if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                <ul class=\"form\">\r\n                    <li>");


            
            #line 179 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 181 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 182 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li>");


            
            #line 184 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 186 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Page.NavigationTitle, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 187 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Page.NavigationTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </li>\r\n                    <li class=\"protected\">");


            
            #line 189 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     Write(Html.LabelFor(m => m.Page.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 190 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Permalink != null && !String.IsNullOrEmpty(Model.Permalink.Name)) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");


            
            #line 191 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden

            
            #line 191 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                               Write(Url.GetPermalink(Model.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 192 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p><i>");


            
            #line 193 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         Write(Piranha.Resources.Page.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");


            
            #line 194 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"input\">\r\n                            ");


            
            #line 196 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                        ");


            
            #line 197 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.ValidationMessageFor(m => m.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <a class=\"locked\"></a>\r\n                    </li>\r\n    " +
"                <li>\r\n                        <label>");


            
            #line 201 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Placement);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n                        <button class=\"btn right\" id=\"btnMove\">");


            
            #line 202 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                          Write(Piranha.Resources.Global.Move);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 203 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.Page.IsStartpage) {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");


            
            #line 204 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementPage);

            
            #line default
            #line hidden
WriteLiteral(" <strong>");


            
            #line 204 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                       Write(Model.Page.Seqno > 1 ? @Piranha.Resources.Global.PlacementAfter : @Piranha.Resources.Global.PlacementBelow);

            
            #line default
            #line hidden
WriteLiteral("</strong> &quot;");


            
            #line 204 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                                                                                   Write(Model.PlaceRef);

            
            #line default
            #line hidden
WriteLiteral("&quot;</p>\r\n");


            
            #line 205 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        } else {

            
            #line default
            #line hidden
WriteLiteral("                        <p>");


            
            #line 206 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                      Write(Piranha.Resources.Global.PlacementStart);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 207 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        <div id=\"placement-edit\" style=\"display:none\">\r\n         " +
"                   ");


            
            #line 209 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input\">\r\n                              " +
"  <select id=\"Page_ParentId\" name=\"Page.ParentId\">\r\n");


            
            #line 212 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     foreach (var p in Model.Parents) {

            
            #line default
            #line hidden
WriteLiteral("                                    <option value=\"");


            
            #line 213 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(p.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");


            
            #line 213 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                     Write(p.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                                        ");


            
            #line 214 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.Raw(p.Title));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 215 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                          ");


            
            #line 218 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.LabelFor(m => m.Page.Seqno));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            <div class=\"input\" id=\"div-seqno\">\r\n               " +
"                 <select id=\"Page_Seqno\" name=\"Page.Seqno\">\r\n");


            
            #line 221 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 foreach (var s in Model.Siblings) {

            
            #line default
            #line hidden
WriteLiteral("                                <option value=\"");


            
            #line 222 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                          Write(s.Seqno);

            
            #line default
            #line hidden
WriteLiteral("\"");


            
            #line 222 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                    Write(s.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 222 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                               Write(s.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 223 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </select>\r\n                            </div>\r\n  " +
"                      </div>\r\n                    </li>\r\n                </ul>\r\n" +
"");


            
            #line 229 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                } else {

            
            #line default
            #line hidden
WriteLiteral("                <ul class=\"form\">\r\n                    <li>\r\n                    " +
"    ");


            
            #line 232 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaTitle, Piranha.Resources.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 234 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextBoxFor(m => m.SiteTree.MetaTitle));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 235 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaTitle)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span class=\"notification\">");


            
            #line 236 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 237 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                    <l" +
"i>\r\n                        ");


            
            #line 241 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.LabelFor(m => m.SiteTree.MetaDescription, Piranha.Resources.SiteTree.MetaDescription));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        <div class=\"input\">\r\n                            ");


            
            #line 243 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                       Write(Html.TextAreaFor(m => m.SiteTree.MetaDescription, new { @rows = 5 }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 244 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (String.IsNullOrEmpty(Model.SiteTree.MetaDescription)) {

            
            #line default
            #line hidden
WriteLiteral("                                <span class=\"notification\">");


            
            #line 245 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 246 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </div>\r\n                    </li>\r\n                </ul>\r" +
"\n");


            
            #line 250 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n        </div>\r\n    </div>\r\n");


            
            #line 254 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!String.IsNullOrEmpty(Model.Template.Preview.ToString())) {

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"grid_3\">\r\n        <div class=\"box pagetemplate\">\r\n            <di" +
"v class=\"title\"><h2>");


            
            #line 257 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(!Model.IsSite ? Model.Template.Name : Model.SiteTree.Name);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n            <div class=\"inner\">\r\n                <div class=\"edit\">\r" +
"\n                    ");


            
            #line 260 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Model.Template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");


            
            #line 265 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n<div>\r\n    <div class=\"grid_12\">\r\n        <div class=\"box main-content\">\r" +
"\n            <table>\r\n                <tr>\r\n                    <td class=\"tools" +
"\">\r\n                        <ul>\r\n                            <li class=\"btn-con" +
"tent ");


            
            #line 274 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               Write(Model.Action != EditModel.ActionType.SEO ? "active" : "");

            
            #line default
            #line hidden
WriteLiteral("\"><a href=\"#\" data-id=\"pnl-content\">");


            
            #line 274 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                             Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 275 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                            <li class=\"btn-settings ");


            
            #line 276 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                Write(Model.Action == EditModel.ActionType.SEO ? "active" : "");

            
            #line default
            #line hidden
WriteLiteral("\"><a href=\"#\" data-id=\"pnl-settings\">");


            
            #line 276 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                               Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 277 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden

            
            #line 278 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                            <li class=\"btn-properties\"><a href=\"#\" data-id=\"pnl-p" +
"roperties\">");


            
            #line 279 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                       Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 280 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden

            
            #line 281 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                            <li class=\"btn-comments\">\r\n");


            
            #line 283 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  
                                    var count = Model.Comments.Where(c => c.Status == Piranha.Entities.Comment.CommentStatus.New).Count() ;
                                

            
            #line default
            #line hidden
WriteLiteral("                                <span ");


            
            #line 286 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                  Write(count == 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(" id=\"comment-notification\" class=\"notification\">");


            
            #line 286 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                          Write(count);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                                <a href=\"#\" data-id=\"pnl-comments\">");


            
            #line 287 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                            </li>\r\n");


            
            #line 289 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden

            
            #line 290 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                             foreach (var ext in Model.Extensions) {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <a href=\"#\"");


            
            #line 292 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(ExtensionManager.Current.GetIconPathByType(ext.Type) != "" ? "style=background-image:url('" + 
                                Url.Content(ExtensionManager.Current.GetIconPathByType(ext.Type)) + "')" : "");

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"pnl-");


            
            #line 293 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                       Write(ExtensionManager.Current.GetInternalIdByType(ext.Type).ToLower());

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                    ");


            
            #line 294 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(ExtensionManager.Current.GetNameByType(ext.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n                            </li>\r\n");


            
            #line 297 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </ul>\r\n                    </td>\r\n                    <td" +
">\r\n                        <div id=\"pnl-content\" class=\"main content-editor ");


            
            #line 301 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                     Write(Model.Action != EditModel.ActionType.SEO ? "" : "hidden");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <div class=\"title\">\r\n                            " +
"    <div id=\"regionbuttons\" class=\"buttons\">\r\n");


            
            #line 304 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     for (int n = 0; n < Model.Regions.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                        <button id=\"");


            
            #line 305 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               Write(Html.Raw("btn_" + Model.Regions[n].InternalId));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn");


            
            #line 305 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                           Write(n > 0 ? "" : " active");

            
            #line default
            #line hidden
WriteLiteral(" region\">");


            
            #line 305 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                                            Write(Model.Regions[n].Name);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");


            
            #line 306 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    <button id=\"btn_attachments\" class=\"btn");


            
            #line 307 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                       Write(Model.Regions.Count == 0 ? " active" : "");

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 307 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                                                                    Write(Piranha.Resources.Page.Attachments);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                                </div>\r\n                              " +
"  <h2 id=\"section-title\">");


            
            #line 309 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Piranha.Resources.Global.Content);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n                            </div>\r\n                            <div class" +
"=\"inner\">\r\n");


            
            #line 312 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 if (Model.Regions.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                                <div id=\"regions\">\r\n                             " +
"       ");


            
            #line 314 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.EditorFor(m => m.Regions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n");


            
            #line 316 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                <div id=\"attachments\" ");


            
            #line 317 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                  Write(Model.Regions.Count > 0 ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                                    ");


            
            #line 318 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                               Write(Html.Partial("Partial/Attachments"));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </div>\r\n                            </div>\r\n   " +
"                     </div>\r\n");


            
            #line 322 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (!Model.IsSite) {

            
            #line default
            #line hidden
WriteLiteral("                        <div id=\"pnl-settings\" class=\"main ");


            
            #line 323 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                       Write(Model.Action == EditModel.ActionType.SEO ? "" : "hidden");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <div class=\"title\"><h2>");


            
            #line 324 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Settings);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div class=\"inner\">\r\n                   " +
"             <ul class=\"form\">\r\n                                    <li>\r\n      " +
"                                  ");


            
            #line 328 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.GroupId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 330 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.DropDownListFor(m => m.Page.GroupId, Model.Groups));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 331 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.DisabledGroups));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div id=\"disable-groups\" class=\"block\">" +
"\r\n");


            
            #line 333 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                               var dGroups = Model.Groups.Where(g => g.Value != Guid.Empty.ToString()).ToList() ; 

            
            #line default
            #line hidden
WriteLiteral("                                            ");


            
            #line 334 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.Partial("Partial/GroupList", new Piranha.Models.Manager.PageModels.GroupListModel() { 
                                                Groups = Model.DisableGroups, Page = Model.Page }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </div>\r\n                               " +
"     </li>\r\n                                    <li>\r\n                          " +
"              ");


            
            #line 339 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <p>");


            
            #line 340 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                      Write(Html.CheckBoxFor(m => m.Page.IsHidden));

            
            #line default
            #line hidden
WriteLiteral(" (");


            
            #line 340 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                               Write(Piranha.Resources.Page.HiddenDescription);

            
            #line default
            #line hidden
WriteLiteral(")</p>\r\n                                    </li>\r\n                               " +
"     <li>");


            
            #line 342 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\"> \r\n                 " +
"                           ");


            
            #line 344 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.Keywords, new { @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 345 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Keywords)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <span class=\"notification\">");


            
            #line 346 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.KeywordsNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 347 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n                                 " +
"       ");


            
            #line 349 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Keywords));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n                                    " +
"<li>");


            
            #line 351 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 353 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextAreaFor(m => m.Page.Description, new { @rows = 3, @placeholder = Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 354 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                             if (Model.Action == EditModel.ActionType.SEO && String.IsNullOrEmpty(Model.Page.Description)) {

            
            #line default
            #line hidden
WriteLiteral("                                                <span class=\"notification\">");


            
            #line 355 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Piranha.Resources.Page.DescriptionNotification);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 356 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                            }

            
            #line default
            #line hidden
WriteLiteral("                                        </div>\r\n                                 " +
"       ");


            
            #line 358 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");


            
            #line 360 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowController) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");


            
            #line 361 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageController,
                                            Piranha.Application.Current.IsMvc ? Piranha.Resources.Page.Route : Piranha.Resources.Page.Template));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 364 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageController, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Controller) ? Model.Template.Controller : "Page" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 365 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageController));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");


            
            #line 367 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden

            
            #line 368 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Piranha.Application.Current.IsMvc && Model.Template.ShowView) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");


            
            #line 369 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageView));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 371 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageView, new { @placeholder = !String.IsNullOrEmpty(Model.Template.View) ? Model.Template.View : "Index" }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 372 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageView));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");


            
            #line 374 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden

            
            #line 375 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                     if (Model.Template.ShowRedirect) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");


            
            #line 376 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 378 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Page.PageRedirect, new { @placeholder = !String.IsNullOrEmpty(Model.Template.Redirect) ? Model.Template.Redirect : Piranha.Resources.Global.Optional }));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                        ");


            
            #line 379 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.ValidationMessageFor(m => m.Page.PageRedirect));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    </li>\r\n");


            
            #line 381 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");


            
            #line 385 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden

            
            #line 386 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.Properties.Count > 0) {

            
            #line default
            #line hidden
WriteLiteral("                        <div id=\"pnl-properties\" class=\"main hidden\">\r\n          " +
"                  <div class=\"title\"><h2>");


            
            #line 388 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Properties);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div class=\"inner\">\r\n                   " +
"             <ul class=\"form\">\r\n");


            
            #line 391 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                 for (int n = 0; n < Model.Properties.Count; n++) {

            
            #line default
            #line hidden
WriteLiteral("                                    <li>");


            
            #line 392 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.LabelFor(m => m.Properties[n], Model.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ");


            
            #line 393 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ");


            
            #line 394 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsDraft));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ");


            
            #line 395 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ");


            
            #line 396 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ");


            
            #line 397 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        ");


            
            #line 398 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                   Write(Html.HiddenFor(m => m.Properties[n].IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        <div class=\"input\">\r\n                  " +
"                          ");


            
            #line 400 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                       Write(Html.TextBoxFor(m => m.Properties[n].Value));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                                    </li>\r\n");


            
            #line 402 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                                </ul>\r\n                            </div>\r\n      " +
"                  </div>\r\n");


            
            #line 406 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden

            
            #line 407 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                         if (Model.EnableComments) {

            
            #line default
            #line hidden
WriteLiteral("                        <div id=\"pnl-comments\" class=\"main content-editor hidden\"" +
">\r\n                            <div class=\"title\"><h2>");


            
            #line 409 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                              Write(Piranha.Resources.Global.Comments);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n                            <div class=\"inner region-body\">\r\n       " +
"                         ");


            
            #line 411 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                           Write(Html.Partial("~/Areas/Manager/Views/Comment/List.cshtml", Model.Comments));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </div>\r\n");


            
            #line 414 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                        ");


            
            #line 415 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                </tr>\r\n            </table>\r\n       " +
" </div>\r\n    </div>\r\n</div>\r\n<div class=\"grid_3 hidden\">\r\n");


            
            #line 423 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
     if (!Model.Page.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"box expandable\">\r\n        <div class=\"title\"><h2>");


            
            #line 425 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                          Write(Piranha.Resources.Global.Versioning);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner optional\">\r\n            <ul class=\"list\">\r" +
"\n                <li>");


            
            #line 428 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.LastPublished);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">\r\n                    ");


            
            #line 429 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.LastPublished > DateTime.MinValue ? Model.Page.LastPublished.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");


            
            #line 430 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Published);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">\r\n                    ");


            
            #line 431 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                Write(Model.Page.Published > DateTime.MinValue ? Model.Page.Published.ToShortDateString() : "");

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");


            
            #line 432 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">");


            
            #line 432 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Updated.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n                <li>");


            
            #line 433 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
               Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral(" <small class=\"right\">");


            
            #line 433 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
                                                                      Write(Model.Page.Created.ToShortDateString());

            
            #line default
            #line hidden
WriteLiteral("</small></li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n");


            
            #line 437 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 439 "..\..\Areas\Manager\Views\Page\Edit.cshtml"
   Html.EndForm() ; 

            
            #line default
            #line hidden

DefineSection("Foot", () => {

WriteLiteral("\r\n <div id=\"boxContent\" class=\"floatbox\">\r\n    <div class=\"bg\"></div>\r\n    <div c" +
"lass=\"box\" style=\"min-width: 510px;min-height:260px;\">\r\n    </div>\r\n</div>\r\n");


});


        }
    }
}
#pragma warning restore 1591
