#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Page\Index.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.PageModels.ListModel>
    {
        public Index()
        {
        }
        public override void Execute()
        {



DefineSection("Head", () => {

WriteLiteral(@"
    <style type=""text/css"">
        ul.sites {
            float: left;
            margin-left: 10px;
            margin-right: 0;
            margin-bottom: 0;
            }
        ul.sites li a.selected {
            border: 0 none;
            padding: 10px 20px 6px;
            }
    </style>
    <script type=""text/javascript"">
        //
        // Sets all hidden fields before submit
        function preSubmit(parentid, seqno) {
            $(""#ParentId"").val(parentid);
            $(""#Seqno"").val(seqno);

            floatBox.show('boxTemplates');

            return false;
        }

        var deletemsg = """);


            
            #line 28 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    Write(Piranha.Resources.Page.MessageDeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\";\r\n\r\n        function formatSitemap() {\r\n            $.each($(\".sitemap li:visib" +
"le\"), function (i, e) {\r\n                if (i % 2 == 1)\r\n                    $(" +
"this).addClass(\"odd\");\r\n                else $(this).removeClass(\"odd\");\r\n      " +
"      });\r\n        }\r\n\r\n        var currmove;\r\n\r\n        $(document).ready(funct" +
"ion () {\r\n            formatSitemap();\r\n\r\n            // Handle the site tree\r\n " +
"           $(\".sitemap .action\").click(function () {\r\n                var li = $" +
"(this).parent().parent();\r\n                li.toggleClass(\"collapsed\");\r\n       " +
"         li.toggleClass(\"expanded\");\r\n                formatSitemap();\r\n        " +
"    });\r\n\r\n            // Set the selected template id\r\n            $(\".template" +
"s\").click(function () {\r\n                $(\"#TemplateId\").val($(this).attr(\"data" +
"-templateid\"));\r\n                $(\"form\").submit();\r\n            });\r\n\r\n       " +
"     // Set the original id\r\n            $(\".copy-page\").live(\'click\', function " +
"() {\r\n                $(\"#OriginalId\").val($(this).attr(\"data-id\"));\r\n          " +
"      $(\"form\").submit();\r\n            });\r\n\r\n            $(\".delete\").click(fun" +
"ction () {\r\n                return confirm(deletemsg);\r\n            });\r\n\r\n     " +
"       // Setup page list\r\n            var options = {\r\n                listClas" +
"s: \'list-js\',\r\n                searchId: \'search\',\r\n                valueNames: " +
"[\'title\', \'template\', \'updated\', \'created\']\r\n            };\r\n            new Lis" +
"t(\'list\', options);\r\n\r\n            // Setup page copy list\r\n            var copy" +
"options = {\r\n                listClass: \'copy-list-js\',\r\n                searchI" +
"d: \'page-search\',\r\n                valueNames: [\'copypage-title\', \'copypage-temp" +
"late\', \'copypage-siteid\']\r\n            };\r\n            new List(\'page-list\', cop" +
"yoptions);\r\n\r\n");


            
            #line 83 "..\..\Areas\Manager\Views\Page\Index.cshtml"
             if (!Model.IsSeoList) {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral(@"
            // Switch between list/tree
            $(""#search"").keyup(function () {
                if ($(this).val() != """") {
                    $("".sitemap"").hide();
                    $(""#list"").show();
                } else {
                    $(""#list"").hide();
                    $("".sitemap"").show();
                }
            });
            ");

WriteLiteral("\r\n");


            
            #line 96 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        });

        function bindMove() {
            $("".move .title a"").click(function () {
                if ($(this).parent().parent().hasClass(""expanded""))
                    alert(""move: "" + currmove + "" below: "" + $(this).parent().parent().attr(""id""));
                else alert(""move: "" + currmove + "" after: "" + $(this).parent().parent().attr(""id""));

                return false;
            });
        }
    </script>
    <!-- Restyle the list a bit to match tree -->
    <style type=""text/css"">
        table.list th:first-child,
        table.list tbody td:first-child > * {
            padding-left: 30px;
            }
    </style>
");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral(" \r\n");


            
            #line 118 "..\..\Areas\Manager\Views\Page\Index.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a onclick=\"floatBox.show(\'boxTemplates\')\" class=\"add\">");


            
            #line 122 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                  Write(Piranha.Resources.Global.ToolbarAdd);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 123 "..\..\Areas\Manager\Views\Page\Index.cshtml"
             if (Model.ActiveSite != "DEFAULT_SITE") {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 124 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    Write(Url.Action("site", new { id = Model.ActiveSite.ToLower() }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 124 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                  Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 125 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <li><a href=\"");


            
            #line 126 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    Write(Url.Action("index"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 126 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                          Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n");


            
            #line 127 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 128 "..\..\Areas\Manager\Views\Page\Index.cshtml"
             if (Model.SitePage[Model.ActiveSiteId] != Guid.Empty) {

            
            #line default
            #line hidden
WriteLiteral("            <li>\r\n                <a href=\"");


            
            #line 130 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    Write(Url.Action("edit", new { @id = Model.SitePage[Model.ActiveSiteId] }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"edit-site\">");


            
            #line 130 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                             Write(Piranha.Resources.Page.EditSite);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");


            
            #line 131 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                 if (Model.SiteWarnings[Model.ActiveSiteId] > 0) {

            
            #line default
            #line hidden
WriteLiteral("                     <span class=\"notification\">");


            
            #line 132 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                           Write(Model.SiteWarnings[Model.ActiveSiteId]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 133 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </li>\r\n");


            
            #line 135 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            }

            
            #line default
            #line hidden

            
            #line 136 "..\..\Areas\Manager\Views\Page\Index.cshtml"
             if (Model.TotalSiteWarnings[Model.ActiveSiteId] > 0) {

            
            #line default
            #line hidden
WriteLiteral("                <li>\r\n                    <a href=\"");


            
            #line 138 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                        Write(Url.Action("seo", new { @id = Model.ActiveSite.ToLower() }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"seo\">SEO</a>\r\n                    <span class=\"notification\">");


            
            #line 139 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                          Write(Model.TotalSiteWarnings[Model.ActiveSiteId]);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                </li>\r\n");


            
            #line 141 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            ");


            
            #line 142 "..\..\Areas\Manager\Views\Page\Index.cshtml"
       Write(Piranha.WebPages.Hooks.Manager.Toolbar.Render(Url, Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </ul>\r\n        <button class=\"search\" title=\"");


            
            #line 144 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                 Write(Piranha.Resources.Global.ToolbarSearch);

            
            #line default
            #line hidden
WriteLiteral("\"></button>");


            
            #line 144 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                   Write(Html.TextBox("search"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n");


});

WriteLiteral("\r\n<div class=\"grid_12\">\r\n");


            
            #line 150 "..\..\Areas\Manager\Views\Page\Index.cshtml"
 using (Html.BeginForm("insert", (string)ViewContext.RouteData.Values["Controller"])) {
    
            
            #line default
            #line hidden
            
            #line 151 "..\..\Areas\Manager\Views\Page\Index.cshtml"
Write(Html.Hidden("TemplateId", Model.Templates.Count == 1 ? Model.Templates[0].Id : Guid.Empty));

            
            #line default
            #line hidden
            
            #line 151 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                               
    
            
            #line default
            #line hidden
            
            #line 152 "..\..\Areas\Manager\Views\Page\Index.cshtml"
Write(Html.Hidden("ParentId"));

            
            #line default
            #line hidden
            
            #line 152 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 153 "..\..\Areas\Manager\Views\Page\Index.cshtml"
Write(Html.Hidden("Seqno", Model.NewSeqno));

            
            #line default
            #line hidden
            
            #line 153 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                         
    
            
            #line default
            #line hidden
            
            #line 154 "..\..\Areas\Manager\Views\Page\Index.cshtml"
Write(Html.Hidden("SiteTree", Model.ActiveSite));

            
            #line default
            #line hidden
            
            #line 154 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                              
    
            
            #line default
            #line hidden
            
            #line 155 "..\..\Areas\Manager\Views\Page\Index.cshtml"
Write(Html.Hidden("OriginalId"));

            
            #line default
            #line hidden
            
            #line 155 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                              

    if (Model.SiteTrees.Count > 1) {

            
            #line default
            #line hidden
WriteLiteral("    <div>\r\n        <ul class=\"sites tabs\">\r\n");


            
            #line 160 "..\..\Areas\Manager\Views\Page\Index.cshtml"
             foreach (var site in Model.SiteTrees) {

            
            #line default
            #line hidden
WriteLiteral("            <li>\r\n                <a href=\"");


            
            #line 162 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    Write(Url.Action("site", "page", new { @id = site.InternalId.ToLower() }));

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 162 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                           Write(site.InternalId == Model.ActiveSite ? "class=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 162 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                                                         Write(site.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n            </li>\r\n");


            
            #line 164 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n");


            
            #line 168 "..\..\Areas\Manager\Views\Page\Index.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("    <ul class=\"sitemap\" ");


            
            #line 169 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    Write(Model.IsSeoList ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n");


            
            #line 170 "..\..\Areas\Manager\Views\Page\Index.cshtml"
         if (!Model.IsSeoList) {

            
            #line default
            #line hidden
WriteLiteral("        <li class=\"header\">\r\n            <span class=\"buttons\"></span>\r\n         " +
"   <span class=\"date\">");


            
            #line 173 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                          Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <span class=\"date\">");


            
            #line 174 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                          Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <span class=\"type\">");


            
            #line 175 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                          Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <span class=\"title\">");


            
            #line 176 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                           Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        </li>\r\n");


            
            #line 178 "..\..\Areas\Manager\Views\Page\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 178 "..\..\Areas\Manager\Views\Page\Index.cshtml"
   Write(Html.Partial(@"~/Areas/Manager/Views/Page/Partial/SiteTree.cshtml", Model.SiteMap));

            
            #line default
            #line hidden
            
            #line 178 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                           
        }

            
            #line default
            #line hidden
WriteLiteral("    </ul>\r\n");


            
            #line 181 "..\..\Areas\Manager\Views\Page\Index.cshtml"
    

            
            #line default
            #line hidden
WriteLiteral("    <table id=\"list\" class=\"list\" ");


            
            #line 182 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                              Write(!Model.IsSeoList ? "style=display:none" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n        <thead>\r\n            <tr>\r\n                <th><span class=\"sort asc\" " +
"data-sort=\"title\">");


            
            #line 185 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                        Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th style=\"width:200px\"><span class=\"sort\" data-sor" +
"t=\"template\">");


            
            #line 186 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                           Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"upda" +
"ted\">");


            
            #line 187 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Updated);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th class=\"date\"><span class=\"sort\" data-sort=\"crea" +
"ted\">");


            
            #line 188 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                   Write(Piranha.Resources.Global.Created);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                <th></th>\r\n            </tr>\r\n        </thead>\r\n   " +
"     <tbody class=\"list-js\">\r\n");


            
            #line 193 "..\..\Areas\Manager\Views\Page\Index.cshtml"
             foreach (var page in Model.Pages) {

            
            #line default
            #line hidden
WriteLiteral("            <tr");


            
            #line 194 "..\..\Areas\Manager\Views\Page\Index.cshtml"
           Write(page.Updated > page.LastPublished ? " class=draft" : "");

            
            #line default
            #line hidden
WriteLiteral(">\r\n                <td class=\"title\"><a href=\"");


            
            #line 195 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                      Write(Url.Action("edit", new { id = page.Id }));

            
            #line default
            #line hidden

            
            #line 195 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                               Write(Html.Raw(Model.IsSeoList ? "?action=seo" : ""));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    ");


            
            #line 196 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                Write(!String.IsNullOrEmpty(page.NavigationTitle) ? page.NavigationTitle : page.Title);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"list-info\">\r\n                        ");


            
            #line 198 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                   Write(Html.Raw(page.LastPublished == DateTime.MinValue ? "<span class=info-unpublished></span>" : (page.Updated > page.LastPublished ? "<span class=info-draft></span>" : "")));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 199 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                   Write(Html.Raw(page.OriginalId != Guid.Empty ? "<span class=info-copy></span>" : ""));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        ");


            
            #line 200 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                   Write(Html.Raw(Model.IsSeoList ? "<span class=notification>" + Model.PageWarnings[page.Id].ToString() + "</span>" : ""));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </a></td>\r\n                <td clas" +
"s=\"template\">");


            
            #line 203 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                Write(page.TemplateName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"updated\">");


            
            #line 204 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                               Write(page.Updated.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"created\">");


            
            #line 205 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                               Write(page.Created.ToString("yyyy-MM-dd"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td class=\"buttons three\">\r\n                    <button cl" +
"ass=\"icon add-after marg\" title=\"");


            
            #line 207 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                          Write(Piranha.Resources.Page.ListAddAfter);

            
            #line default
            #line hidden
WriteLiteral("\" onclick=\"return preSubmit(\'");


            
            #line 207 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                           Write(page.ParentId);

            
            #line default
            #line hidden
WriteLiteral("\', ");


            
            #line 207 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                                             Write(page.Seqno + 1);

            
            #line default
            #line hidden
WriteLiteral(")\" type=\"submit\"></button>\r\n                    <button class=\"icon add-below mar" +
"g\" title=\"");


            
            #line 208 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                          Write(Piranha.Resources.Page.ListAddBelow);

            
            #line default
            #line hidden
WriteLiteral("\" onclick=\"return preSubmit(\'");


            
            #line 208 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                           Write(page.Id);

            
            #line default
            #line hidden
WriteLiteral("\', 1)\" type=\"submit\"></button>\r\n");


            
            #line 209 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                     if (page.Pages.Count == 0 && User.HasAccess("ADMIN_PAGE_PUBLISH")) {

            
            #line default
            #line hidden
WriteLiteral("                    <a href=\"");


            
            #line 210 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                        Write(Url.Action("delete", "page", new { id = page.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 210 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                    Write(Piranha.Resources.Page.ListDelete);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"icon delete\"></a>\r\n");


            
            #line 211 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </td>\r\n            </tr>\r\n");


            
            #line 214 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n        <tfoot>\r\n            <tr>\r\n                <td colspan=" +
"\"5\"></td>\r\n            </tr>\r\n        </tfoot>\r\n    </table>\r\n");


            
            #line 222 "..\..\Areas\Manager\Views\Page\Index.cshtml"
    
}

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");


DefineSection("Foot", () => {

WriteLiteral("\r\n<div id=\"boxTemplates\" class=\"floatbox\">\r\n    <div class=\"bg\"></div>\r\n    <div " +
"class=\"box\">\r\n        <div class=\"title\">\r\n            <ul class=\"box-tabs\">\r\n  " +
"              <li class=\"selected\"><a href=\"#create-new\">");


            
            #line 232 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                      Write(Piranha.Resources.Page.PopupTypeTitle);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n                <li><a href=\"#create-copy\">");


            
            #line 233 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                      Write(Piranha.Resources.Page.CreateCopy);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            </ul>\r\n            <a class=\"close-btn right\" data-id=\"box" +
"Templates\"></a>\r\n            <div class=\"clear\"></div>\r\n        </div>\r\n        " +
"<div id=\"create-new\" class=\"inner\">\r\n");


            
            #line 239 "..\..\Areas\Manager\Views\Page\Index.cshtml"
             foreach (var template in Model.Templates) {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"templates ");


            
            #line 240 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                              Write(Model.Templates.Count > 6 ? "compressed" : (Model.Templates.Count == 1 ? "one" : ""));

            
            #line default
            #line hidden
WriteLiteral(" left\" data-templateid=\"");


            
            #line 240 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                                                            Write(template.Id);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                <h3>");


            
            #line 241 "..\..\Areas\Manager\Views\Page\Index.cshtml"
               Write(template.Name);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n                <div class=\"preview\">\r\n                    ");


            
            #line 243 "..\..\Areas\Manager\Views\Page\Index.cshtml"
               Write(template.Preview);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n                <p>");


            
            #line 245 "..\..\Areas\Manager\Views\Page\Index.cshtml"
              Write(template.Description);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n            </div>\r\n");


            
            #line 247 "..\..\Areas\Manager\Views\Page\Index.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"            <div class=""clear""></div>
        </div>
        <div id=""create-copy"" class=""inner hidden"" style=""width:660px;max-height:460px;overflow:scroll;"">
            <ul class=""form"" style=""position:fixed;width:645px"">
                <li><label>Search</label>
                    <div class=""input""><input type=""text"" id=""page-search"" /></div>
                </li>
            </ul>
            <table class=""list"" id=""page-list"" style=""margin-top:34px;"">
                <thead>
                    <tr>
                        <th><span class=""sort asc"" data-sort=""copypage-title"">");


            
            #line 259 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                         Write(Piranha.Resources.Global.Title);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                        <th><span class=\"sort\" data-sort=\"copypage-" +
"template\">");


            
            #line 260 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                        Write(Piranha.Resources.Global.Type);

            
            #line default
            #line hidden
WriteLiteral("</span></th>\r\n                        <th><span class=\"sort\" data-sort=\"copypage-" +
"siteid\">Site tree</span></th>\r\n                    </tr>\r\n                </thea" +
"d>\r\n                <tbody class=\"copy-list-js\">\r\n");


            
            #line 265 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                 foreach (var page in Model.AllPages) {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td class=\"copypage-title\"><a c" +
"lass=\"copy-page\" data-id=\"");


            
            #line 267 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                            Write(page.Id);

            
            #line default
            #line hidden
WriteLiteral("\" href=\"#\"> ");


            
            #line 267 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                                                                 Write(!String.IsNullOrEmpty(page.NavigationTitle) ? page.NavigationTitle : page.Title);

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                        <td class=\"copypage-template\">");


            
            #line 268 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                                 Write(page.TemplateName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td class=\"copypage-siteid\">");


            
            #line 269 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                                               Write(page.SiteTreeName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    </tr>\r\n");


            
            #line 271 "..\..\Areas\Manager\Views\Page\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n        </div>\r\n    </div>\r\n</div" +
">\r\n");


});


        }
    }
}
#pragma warning restore 1591
