#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Page
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Page\Siblings.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Page/Siblings.cshtml")]
    public partial class Siblings : System.Web.Mvc.WebViewPage<List<Piranha.Models.Manager.PageModels.EditModel.PagePlacement>>
    {
        public Siblings()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Page\Siblings.cshtml"
  
    Layout = "";


            
            #line default
            #line hidden
WriteLiteral("<select id=\"Page_Seqno\" name=\"Page.Seqno\">\r\n");


            
            #line 7 "..\..\Areas\Manager\Views\Page\Siblings.cshtml"
 foreach (var s in Model) {

            
            #line default
            #line hidden
WriteLiteral("<option value=\"");


            
            #line 8 "..\..\Areas\Manager\Views\Page\Siblings.cshtml"
          Write(s.Seqno);

            
            #line default
            #line hidden
WriteLiteral("\"");


            
            #line 8 "..\..\Areas\Manager\Views\Page\Siblings.cshtml"
                    Write(s.IsSelected ? " selected=selected" : "");

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 8 "..\..\Areas\Manager\Views\Page\Siblings.cshtml"
                                                               Write(s.Title);

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 9 "..\..\Areas\Manager\Views\Page\Siblings.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("</select>\r\n");


        }
    }
}
#pragma warning restore 1591
