#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Extensions
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Extensions/ImageRegion.cshtml")]
    public partial class ImageRegion : System.Web.Mvc.WebViewPage<Piranha.Extend.Regions.ImageRegion>
    {
        public ImageRegion()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
  
    Layout = "";

    var btnId = @ViewData.TemplateInfo.GetFullHtmlFieldId("myButton");
    var boxId = @ViewData.TemplateInfo.GetFullHtmlFieldId("myImageBox");
    var retId = @ViewData.TemplateInfo.GetFullHtmlFieldId("Id");
    var nameId = @ViewData.TemplateInfo.GetFullHtmlFieldId("Name");
    var altId = @ViewData.TemplateInfo.GetFullHtmlFieldId("Description");
    var imgPrev = @ViewData.TemplateInfo.GetFullHtmlFieldId("Preview");
    var btnRm = @ViewData.TemplateInfo.GetFullHtmlFieldId("btnRemove");


            
            #line default
            #line hidden
WriteLiteral("<script type=\"text/javascript\">\r\n    var thumbpath = \'");


            
            #line 15 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                Write(Url.GetThumbnailBaseUrl());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n\r\n    $(document).ready(function () {\r\n        var m = new piranha.media(\'");


            
            #line 18 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                              Write(btnId);

            
            #line default
            #line hidden
WriteLiteral("\', \'");


            
            #line 18 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                                        Write(boxId);

            
            #line default
            #line hidden
WriteLiteral("\', function (data) {\r\n            $(\'#");


            
            #line 19 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(retId);

            
            #line default
            #line hidden
WriteLiteral("\').val(data.Id);\r\n            $(\'#");


            
            #line 20 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(nameId);

            
            #line default
            #line hidden
WriteLiteral("\').val(data.DisplayName);\r\n            $(\'#");


            
            #line 21 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(altId);

            
            #line default
            #line hidden
WriteLiteral("\').val(data.Description);\r\n            $(\'#");


            
            #line 22 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(imgPrev);

            
            #line default
            #line hidden
WriteLiteral("\').attr(\'src\', thumbpath + \'/\' + data.Id + \'/71\');\r\n        });\r\n        $(\'#");


            
            #line 24 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
       Write(btnRm);

            
            #line default
            #line hidden
WriteLiteral("\').click(function () {\r\n            $(\'#");


            
            #line 25 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(retId);

            
            #line default
            #line hidden
WriteLiteral("\').val(\'");


            
            #line 25 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                         Write(Guid.Empty);

            
            #line default
            #line hidden
WriteLiteral("\');\r\n            $(\'#");


            
            #line 26 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(nameId);

            
            #line default
            #line hidden
WriteLiteral("\').val(\'\');\r\n            $(\'#");


            
            #line 27 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(altId);

            
            #line default
            #line hidden
WriteLiteral("\').val(\'\');\r\n            $(\'#");


            
            #line 28 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(imgPrev);

            
            #line default
            #line hidden
WriteLiteral("\').attr(\'src\', \'\');\r\n            return false;\r\n        });\r\n    });\r\n</script>\r\n" +
"<div class=\"box\" style=\"width:71px;height:71px;float:right;margin:14px;border-co" +
"lor:#e2e2e2;\">\r\n    <img id=\"");


            
            #line 34 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
        Write(imgPrev);

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");


            
            #line 34 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                       Write(Url.GetThumbnailUrl(Model.Id, 71));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 34 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                                                                Write(Model.Description);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n</div>\r\n<div style=\"margin-right:90px;\">\r\n    <ul class=\"form\" style=\"paddi" +
"ng-bottom:4px;\">\r\n        <li>\r\n            ");


            
            #line 39 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
       Write(Html.LabelFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"upload\">\r\n                ");


            
            #line 41 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(Html.HiddenFor(m => m.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n                <button type=\"button\" id=\"");


            
            #line 42 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                                     Write(btnId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn right\">");


            
            #line 42 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
                                                               Write(Piranha.Resources.Global.ChooseFile);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                <div class=\"input\">\r\n                    ");


            
            #line 44 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
               Write(Html.TextBoxFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n            </div>\r\n        </li>\r\n        <li>\r\n            ");


            
            #line 48 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
       Write(Html.LabelFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n            <div class=\"input\">\r\n                ");


            
            #line 50 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(Html.TextBoxFor(m => m.Description));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </li>\r\n    </ul>\r\n    <button id=\"");


            
            #line 53 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
           Write(btnRm);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"btn\" style=\"margin-left:14px;margin-bottom:14px;\">Remove current image</" +
"button>\r\n</div>\r\n<div id=\"");


            
            #line 55 "..\..\Areas\Manager\Views\Extensions\ImageRegion.cshtml"
    Write(boxId);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"floatbox\">\r\n    <div class=\"bg\"></div>\r\n    <div class=\"box\" style=\"min-" +
"width:510px;min-height:260px;\">\r\n    </div>\r\n</div>\r\n");


        }
    }
}
#pragma warning restore 1591
