#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Category
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Category/Edit.cshtml")]
    public partial class Edit : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.CategoryModels.EditModel>
    {
        public Edit()
        {
        }
        public override void Execute()
        {



DefineSection("Head", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        $(document).ready(function () {\r\n " +
"           $(\'#Category_Name\').focus();\r\n        });\r\n    </script>\r\n");


});

WriteLiteral("\r\n");


DefineSection("Toolbar", () => {

WriteLiteral("\r\n");


            
            #line 11 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.Partial("Partial/Tabs"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"toolbar\">\r\n    <div class=\"inner\">\r\n        <ul>\r\n            <li><" +
"a class=\"save submit\">");


            
            #line 15 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                                  Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 16 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                    Write(Url.Action("delete", new { id = Model.Category.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"delete\">");


            
            #line 16 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                                                                                          Write(Piranha.Resources.Global.ToolbarDelete);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 17 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                    Write(Url.Action("index", "category"));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"back\">");


            
            #line 17 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                                                                   Write(Piranha.Resources.Global.ToolbarBack);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n            <li><a href=\"");


            
            #line 18 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                    Write(Url.Action("edit", new { id = Model.Category.Id }));

            
            #line default
            #line hidden
WriteLiteral("\" class=\"refresh\">");


            
            #line 18 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                                                                                         Write(Piranha.Resources.Global.ToolbarReload);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        </ul>\r\n        <div class=\"clear\"></div>\r\n    </div>\r\n</div>\r\n" +
"");


});

WriteLiteral("\r\n");


            
            #line 24 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
   Html.BeginForm() ; 

            
            #line default
            #line hidden

            
            #line 25 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Category.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 26 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Category.PermalinkId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 27 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Category.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 28 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Category.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 29 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.IsNew));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 30 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Id));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 31 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 32 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
Write(Html.HiddenFor(m => m.Permalink.Created));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"grid_12\">\r\n    <div class=\"box\">\r\n        <div class=\"title\"><h2>");


            
            #line 35 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                          Write(Piranha.Resources.Global.Information);

            
            #line default
            #line hidden
WriteLiteral("</h2></div>\r\n        <div class=\"inner\">\r\n            <ul class=\"form\">\r\n        " +
"        <li>\r\n                    ");


            
            #line 39 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
               Write(Html.LabelFor(m => m.Category.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 41 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.Category.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    ");


            
            #line 42 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
               Write(Html.ValidationMessageFor(m => m.Category.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li class=\"protected\">\r\n                " +
"    ");


            
            #line 45 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
               Write(Html.LabelFor(m => m.Category.Permalink));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 46 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                 	if (!Model.Category.IsNew) {

            
            #line default
            #line hidden
WriteLiteral("                    <p>");


            
            #line 47 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                  Write(Piranha.WebPages.WebPiranha.GetSiteUrl());

            
            #line default
            #line hidden

            
            #line 47 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                                                           Write(Url.GetPermalink(Model.Category.Permalink).ToLower());

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 48 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                    } else {

            
            #line default
            #line hidden
WriteLiteral("                    <p><i>");


            
            #line 49 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                     Write(Piranha.Resources.Category.PermalinkDescription);

            
            #line default
            #line hidden
WriteLiteral("</i></p>\r\n");


            
            #line 50 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"input\">\r\n                        ");


            
            #line 52 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                   Write(Html.TextBoxFor(m => m.Permalink.Name));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    <a class=\"locked\"></a>\r\n                </li>\r\n      " +
"          <li>\r\n                    ");


            
            #line 56 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
               Write(Html.LabelFor(m => m.Category.Description));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 58 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                   Write(Html.TextAreaFor(m => m.Category.Description));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n                <li>\r\n                    ");


            
            #line 61 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
               Write(Html.LabelFor(m => m.Category.ParentId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div class=\"input\">\r\n                        ");


            
            #line 63 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                   Write(Html.DropDownListFor(m => m.Category.ParentId, Model.Categories));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n");


            
            #line 68 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
     if (Model.Extensions.Count > 0) {
        
            
            #line default
            #line hidden
            
            #line 69 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
   Write(Html.EditorFor(m => m.Extensions));

            
            #line default
            #line hidden
            
            #line 69 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
                                          
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");


            
            #line 72 "..\..\Areas\Manager\Views\Category\Edit.cshtml"
   Html.EndForm() ; 

            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
