#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Piranha.Areas.Manager.Views.Content
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
    using Piranha.Web;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Manager/Views/Content/Popup.cshtml")]
    public partial class Popup : System.Web.Mvc.WebViewPage<Piranha.Models.Manager.ContentModels.PopupModel>
    {
        public Popup()
        {
        }
        public override void Execute()
        {



            
            #line 3 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
  
    Layout = "";
    var first = true;


            
            #line default
            #line hidden
WriteLiteral("<div class=\"title\">\r\n    <ul class=\"box-tabs\">\r\n        <li class=\"selected\"><a c" +
"lass=\"btn-media-existing\"href=\"#attach-existing\">");


            
            #line 9 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                             Write(Piranha.Resources.Content.ChooseExisting);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n        <li><a href=\"#attach-new\" class=\"btn-media-new\">");


            
            #line 10 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                   Write(Piranha.Resources.Content.UploadNew);

            
            #line default
            #line hidden
WriteLiteral("</a></li>\r\n    </ul>\r\n    <a class=\"close-btn right\" data-id=\"boxContent\"></a>\r\n " +
"   <div class=\"clear\"></div>\r\n</div>\r\n<div id=\"attach-existing\" class=\"inner med" +
"ia-existing gallery ");


            
            #line 15 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                          Write(Model.Content.Count > 12 ? "gallery-compressed" : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 16 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
     foreach (var content in Model.Content) {

            
            #line default
            #line hidden
WriteLiteral("        <div class=\"gallery-item ");


            
            #line 17 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                             Write(Model.Content.Count > 12 ? "compressed" : "");

            
            #line default
            #line hidden
WriteLiteral("\">\r\n");


            
            #line 18 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
             if (first && content.ParentId != Guid.Empty) {

            
            #line default
            #line hidden
WriteLiteral("            <img class=\"folder\" data-id=\"");


            
            #line 19 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                    Write(content.Id);

            
            #line default
            #line hidden
WriteLiteral("\" src=\"~/res.ashx/areas/manager/content/img/ico-folder-up-96.png\" />\r\n");


            
            #line 20 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
            } else {

            
            #line default
            #line hidden
WriteLiteral("            <img");


            
            #line 21 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
            Write(content.IsFolder ? " class=folder" : (!content.IsImage ? " class=document" : ""));

            
            #line default
            #line hidden
WriteLiteral(" data-id=\"");


            
            #line 21 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                        Write(content.Id);

            
            #line default
            #line hidden
WriteLiteral("\" src=\"");


            
            #line 21 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                                          Write(Url.GetThumbnailUrl(content.Id, 96));

            
            #line default
            #line hidden
WriteLiteral("\" title=\"");


            
            #line 21 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                                                                                       Write(content.AlternateText);

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"");


            
            #line 21 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                                                                                                                    Write(content.AlternateText);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n");


            
            #line 22 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("            <p><small>");


            
            #line 23 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                 Write(content.DisplayName);

            
            #line default
            #line hidden
WriteLiteral("</small></p>\r\n        </div>\r\n");


            
            #line 25 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
        first = false ;
    }

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"clear\"></div>\r\n    <div class=\"loader\"></div>\r\n</div>\r\n<div id=\"a" +
"ttach-new\" class=\"inner media-new hidden\">\r\n    <ul class=\"form\">\r\n        <li><" +
"label>");


            
            #line 32 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
              Write(Piranha.Resources.Content.Upload);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div class=\"upload\">\r\n                <input type=\"file\" cl" +
"ass=\"media-new-file\" id=\"new-file\" name=\"new-file\" data-id=\"upload_name\" />\r\n   " +
"             <button class=\"btn blue file\" data-id=\"new-file\">");


            
            #line 35 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                            Write(Piranha.Resources.Global.ChooseFile);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                <div class=\"input\">\r\n                    <input id=\"up" +
"load_name\" type=\"text\" />\r\n                </div>\r\n            </div>\r\n        <" +
"/li>\r\n        <li>\r\n            <label>");


            
            #line 42 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
              Write(Piranha.Resources.Content.ParentId);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div class=\"input\">\r\n                <select class=\"new-par" +
"entid\">\r\n");


            
            #line 45 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                     foreach (var f in Model.Folders) {

            
            #line default
            #line hidden
WriteLiteral("                    <option value=\"");


            
            #line 46 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                              Write(f.Value);

            
            #line default
            #line hidden
WriteLiteral("\" ");


            
            #line 46 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                         Write(f.Value == Model.SelectedFolder ? "selected=true" : "");

            
            #line default
            #line hidden
WriteLiteral(">");


            
            #line 46 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                                                                                  Write(Html.Raw(f.Text));

            
            #line default
            #line hidden
WriteLiteral("</option>\r\n");


            
            #line 47 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </select>\r\n            </div>\r\n        </li>\r\n        <li><label>" +
"");


            
            #line 51 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
              Write(Piranha.Resources.Global.Name);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div class=\"input\"><input type=\"text\" class=\"new-name\" /></" +
"div>\r\n        </li>\r\n        <li><label>");


            
            #line 54 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
              Write(Piranha.Resources.Content.AlternateText);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div class=\"input\"><input type=\"text\" class=\"new-alt\" /></d" +
"iv>\r\n        </li>\r\n        <li><label>");


            
            #line 57 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
              Write(Piranha.Resources.Global.Description);

            
            #line default
            #line hidden
WriteLiteral("</label>\r\n            <div class=\"input\"><textarea rows=\"4\" class=\"new-desc\"></te" +
"xtarea></div>\r\n        </li>\r\n    </ul>\r\n    <button class=\"btn media-new-upload" +
" right\">");


            
            #line 61 "..\..\Areas\Manager\Views\Content\Popup.cshtml"
                                          Write(Piranha.Resources.Global.ToolbarSave);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n    <div class=\"clear\"></div>\r\n    <div class=\"loader\"></div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
